[FRNT- 456] implement radio button
woly-ui/woly pull request #103
Opened 2021-04-27 11:25 UTC by Irinaristova

2021-04-29 09:10 UTC, tatinacher requested changes

2021-04-29 09:10 UTC, tatinacher commented on src/ui/molecules/radio-button/usage.mdx
> +        <RadioButton
Не работает смена установка в состояние checked с клавиатуры на первое нажатие enter

2021-04-29 09:10 UTC, tatinacher commented on src/ui/molecules/radio-button/index.tsx
> +  name: string;
отсортируй плз

2021-04-29 09:10 UTC, tatinacher commented on src/ui/molecules/radio-button/index.tsx
> +    margin-right: var(--local-gap);
погляди в макетах, у тебя расстояние между радиобаттоном и текстом меняется в зависимости от размера контейнера, а у тебя --local-gap констанста

2021-04-30 12:18 UTC, sergeysova requested changes

2021-04-30 12:18 UTC, sergeysova commented on src/lib/box-styles.tsx
> +  --woly-border-width: 2px;
А зачем менять ширину бордеров отдельно для primary?

Ширина бордеров должна быть везде одинакова, поэтому она не в variants

2021-04-30 12:18 UTC, sergeysova commented on src/ui/molecules/radio-button/index.tsx
> +      });
А тут есть отписка от keyboard event?

2021-05-07 12:23 UTC, merged