[FRNT-476] Implement secondary variant
woly-ui/woly pull request #104
Opened 2021-04-27 11:45 UTC by Irinaristova

2021-04-29 08:41 UTC, tatinacher approved these changes

2021-04-30 12:51 UTC, sergeysova requested changes

2021-04-30 12:51 UTC, sergeysova commented on src/ui/atoms/button-icon/usage.mdx
> +import {ButtonIcon} from 'ui';
В этом файле разъехалось оформление кода.
Запусти пожалуйста на нем prettier и eslint

2021-05-04 09:01 UTC, sergeysova commented
снова конфликты

2021-05-04 16:24 UTC, merged