[FRNT-493] Implement upload area component
woly-ui/woly pull request #107
Opened 2021-04-30 10:05 UTC by Irinaristova

2021-04-30 12:21 UTC, sergeysova requested changes

2021-04-30 12:21 UTC, sergeysova commented on src/lib/box-styles.tsx
> +  --woly-rounding: 3px;
у нас же скругление в 3px? Почему сейчас меняется?

2021-04-30 12:21 UTC, sergeysova commented on src/ui/atoms/button/index.tsx
> -  children?: never;
Почему удалено?

2021-04-30 12:21 UTC, sergeysova commented on src/ui/atoms/upload-area/index.tsx
> +      background: rgba(110, 59, 254, 0.05);
Почему цвет захаркожен?

2021-04-30 12:21 UTC, sergeysova commented on src/ui/atoms/upload-area/index.tsx
> +    --local-background-color: rgba(110, 59, 254, 0.05);
И этот тоже, откуда берется?

2021-04-30 12:51 UTC, Irinaristova commented on src/ui/atoms/upload-area/index.tsx
> +      background: rgba(110, 59, 254, 0.05);
заведу задачу

2021-05-04 09:00 UTC, sergeysova approved these changes

2021-05-04 09:00 UTC, sergeysova commented
конфликты

2021-05-04 14:29 UTC, tatinacher requested changes

2021-05-04 14:29 UTC, tatinacher commented on src/ui/atoms/upload-area/usage.mdx
> +  <Text type="L">Scrolled UploadArea component with huge data&nbsp;</Text>
На фокус и скролл вниз overlay тоже съезжает
<img width="851" alt="Снимок экрана 2021-05-04 в 17 24 03" src="https://user-images.githubusercontent.com/28189463/117018903-9fa49980-acfd-11eb-9bac-a3fb2adf9512.png">

2021-05-04 14:29 UTC, tatinacher commented on src/ui/atoms/upload-area/usage.mdx
> +| `center`   | `boolean`         | `false`     | Whether the component has benn centred or not                     |
has been :)

2021-05-04 14:29 UTC, tatinacher commented on src/ui/molecules/input-password/index.tsx
> +export const InputPassword = (styled(InputPasswordBase)`
это тут зачем?

2021-05-04 14:50 UTC, Irinaristova commented on src/ui/molecules/input-password/index.tsx
> +export const InputPassword = (styled(InputPasswordBase)`
это из мастер ветки подтянулось

2021-05-07 12:24 UTC, merged