[FRNT-506] Rewrite list
woly-ui/woly pull request #108
Opened 2021-05-04 18:15 UTC by tatinacher

Separate list container and list item

- FRNT-506

2021-05-05 10:16 UTC, sergeysova requested changes

2021-05-05 10:16 UTC, sergeysova commented on src/ui/atoms/list/usage.mdx
> +name: list-new
```suggestion
name: list-container
```

2021-05-05 10:16 UTC, sergeysova commented on src/ui/atoms/list/usage.mdx
> +name: list-new
Из этого названия генерируются импорты

2021-05-07 10:28 UTC, Irinaristova commented on src/ui/atoms/list/index.tsx
> +interface ElementsProps {
мб лучше назвать ListElementsProps? просто ElementsProps ничего не говорит

2021-05-07 10:28 UTC, Irinaristova commented on src/ui/atoms/list/index.tsx
> +  text: string;
а тут всегда будет только текст? здесь нельзя передавать компонент?

2021-05-07 10:28 UTC, Irinaristova commented on src/ui/atoms/list/index.tsx
> +  background-color: var(--woly-canvas);
а что это за цвет такой? мб я не увидела, но вроде он не объявлен здесь и в палитре его нет

2021-05-07 10:28 UTC, Irinaristova commented on src/ui/atoms/list/index.tsx
> +  color: var(--woly-canvas-text-default);
мб лучше было бы объявить в локальной переменной? этот цвет разве не будет меняться?

2021-05-07 10:28 UTC, Irinaristova commented on src/ui/atoms/list/index.tsx
> +  color: var(--woly-canvas-text-default);
он на 78 строчке в состоянии disabled становится другим

2021-05-07 10:28 UTC, Irinaristova commented on src/ui/atoms/list/index.tsx
> +    background-color: var(--woly-canvas-disabled);
а изначально у контейнера вообще нет bg? мб он transparent?

2021-05-07 10:28 UTC, Irinaristova commented on src/ui/atoms/surface/index.tsx
> +  background-color: var(--woly-canvas);
такого цвета нет в палитре

2021-05-07 12:25 UTC, merged