FRNT-541: fix button padding
woly-ui/woly pull request #120
Opened 2021-05-23 13:56 UTC by Irinaristova

2021-05-25 09:58 UTC, sergeysova requested changes

2021-05-25 09:58 UTC, sergeysova commented on src/ui/atoms/button/index.tsx
> +  }
зачем?

2021-05-27 15:40 UTC, Irinaristova commented on src/ui/atoms/button/index.tsx
> +  }
иначе там появляется дефолтный паддинг в 1px и компонент размера none становится больше 24px

2021-05-28 10:54 UTC, tatinacher commented on src/ui/atoms/button/index.tsx
> +  }
может нам на весь проект normalize.css подключить?

2021-05-28 10:55 UTC, Irinaristova commented on src/ui/atoms/button/index.tsx
> +  }
было бы круто)

2021-06-07 10:39 UTC, sergeysova commented on src/ui/atoms/button/index.tsx
> +  }
Но его точно нет никакого смысла добавлять в библиотеку

2021-06-07 10:39 UTC, sergeysova approved these changes

2021-06-07 10:39 UTC, merged