FRNT-499 create toast component
woly-ui/woly pull request #121
Opened 2021-05-24 09:50 UTC by Irinaristova

2021-05-25 09:46 UTC, sergeysova requested changes

2021-05-25 09:46 UTC, sergeysova commented on src/lib/global.ts
> +
```suggestion
```

2021-05-25 09:46 UTC, sergeysova commented on src/ui/molecules/toast/index.tsx
> +    {icon && <span data-toast-icon>{icon}</span>}
```suggestion
    {icon && <span data-icon="toast">{icon}</span>}
```

2021-05-28 11:26 UTC, tatinacher requested changes

2021-05-31 09:41 UTC, Irinaristova commented on src/ui/molecules/toast/usage.mdx
> +          <Button
на это надо заводить задачку, потому что это проблема всех вложенных компонентов

2021-06-07 10:42 UTC, sergeysova requested changes

2021-06-07 10:42 UTC, sergeysova commented on src/ui/molecules/toast/index.tsx
> +  outlined?: boolean;
У нас же не может быть outlined, он скорее default/base или primary

2021-06-10 13:45 UTC, Irinaristova commented on src/ui/molecules/toast/index.tsx
> +  outlined?: boolean;
а разве не все компоненты могут быть во всех палитрах и в разных вариантах отрисовки?

2021-06-16 16:07 UTC, tatinacher requested changes

2021-06-16 16:07 UTC, tatinacher commented on src/ui/molecules/toast/usage.mdx
> +`Toasts` are lightweight notifications designed to mimic the push notifications.
Мб в единственном числе писать?

2021-06-16 16:07 UTC, tatinacher commented on src/ui/molecules/toast/usage.mdx
> +`Toasts` are lightweight notifications designed to mimic the push notifications.
А то как будто компонент называется не Toast а Toasts

2021-06-16 16:07 UTC, tatinacher commented on src/ui/molecules/toast/usage.mdx
> +| ---------- | ------------------ | ------------- | --------------------------------------------------------------------- |
пропсов не хватает

2021-06-17 10:42 UTC, sergeysova requested changes

2021-06-17 10:42 UTC, sergeysova commented on src/ui/molecules/toast/index.tsx
> +  outlined?: boolean;
Мб обновим этот компонент в соответствие с матрицей?

```jsx
<Toast variant="primary" weight="2" />
```

2021-06-17 10:42 UTC, sergeysova commented on src/ui/molecules/toast/usage.mdx
> +          <Button
@Irinaristova Заведешь задачу?

2021-06-18 16:26 UTC, sergeysova approved these changes

2021-06-18 16:26 UTC, merged