[FRNT-485]: Generate map of component states
woly-ui/woly pull request #122
Opened 2021-05-25 15:40 UTC by tatinacher

Generate map of component states

- FRNT-485

2021-06-07 10:44 UTC, sergeysova approved these changes

2021-06-07 12:31 UTC, purplecandle requested changes
В целом хорошо, нужно исправить в паре мест

2021-06-07 12:31 UTC, purplecandle commented on src/lib/map-generation.tsx
> +};
тут вопросов нет, единственное что я адаптировал решение через рекурсию, нужно будет потом подумать как их объединить в одну функцию)
и тут есть лишние вычисления, так как сперва нужно найти массив всех комбинаций, и потом смешать с осями `x` и `y`,  а не находить эти комбинации каждый раз в каждой итерации

2021-06-07 12:31 UTC, purplecandle commented on src/ui/atoms/chip/state-props.tsx
> +import { GenerateMap, SizeBlock } from '../../../lib/map-generation';
импорт из `lib/map-generation`

2021-06-07 12:31 UTC, purplecandle commented on src/ui/atoms/button/state-props.tsx
> +import { GenerateMap, SizeBlock } from '../../../lib/map-generation';
импорт из `lib/map-generation`

2021-06-07 12:31 UTC, purplecandle commented on src/ui/atoms/button-icon/state-props.tsx
> +import { GenerateMap, SizeBlock } from '../../../lib/map-generation';
импорт из `lib/map-generation`

2021-06-07 14:04 UTC, sergeysova commented on src/ui/atoms/button-icon/state-props.tsx
> +import { GenerateMap, SizeBlock } from '../../../lib/map-generation';
```suggestion
import { GenerateMap, SizeBlock } from 'lib/map-generation';
```

Можно сразу подкинуть code suggestion, чтобы было проще

2021-06-18 18:03 UTC, Irinaristova commented on src/lib/map-generation.tsx
> +  Object.keys(otherProps).forEach((key: string) => {
а через reduce тут разве нельзя?

2021-06-21 08:50 UTC, tatinacher commented on src/lib/map-generation.tsx
> +  const variantsMap = generateMap({ y: sizes, x: variants, otherProps });
любые пропсы состояний компонента

2021-06-21 09:41 UTC, sergeysova approved these changes

2021-06-21 09:41 UTC, merged