create tab ana tabbar component
woly-ui/woly pull request #123
Opened 2021-05-27 15:09 UTC by Irinaristova

2021-05-28 11:37 UTC, tatinacher requested changes

2021-05-28 11:37 UTC, tatinacher commented on src/ui/molecules/tabs/usage.mdx
> +</Playground>
Нет таблицы с пропсами

2021-05-28 11:37 UTC, tatinacher commented on src/ui/molecules/tabs/index.tsx
> +  href,
Думаю стоит добавить состояние active, для показа в списке активного таба

2021-05-28 11:37 UTC, tatinacher commented on src/ui/molecules/tabs/index.tsx
> +    border-bottom: var(--woly-border-width) solid var(--woly-focus);
по клике на tab прыгает нижняя граница контейнера

2021-05-28 11:37 UTC, tatinacher commented on src/ui/molecules/tabs/index.tsx
> +  <TabItemContainer href={href} data-outlined={outlined} onClick={onClick} variant={variant}>
С клавиатуры фокусится одновременно таб и кнопка внутри, т.е. я не могу просто табнуть на вкладку, одновременно кликается и кнопка

2021-05-28 19:24 UTC, purplecandle commented on src/ui/molecules/tabs/index.tsx
> +    border-bottom: var(--woly-border-width) solid var(--woly-focus);
Да, тоже заметил это

2021-06-07 10:49 UTC, sergeysova requested changes

2021-06-07 10:49 UTC, sergeysova commented on src/ui/molecules/tabs/index.tsx
> +});
```suggestion
const mapTabItem = (properties: TabItemProps & Variant) => ({
  'data-active': properties.active ?? false,
  'data-variant': properties.variant ?? 'secondary',
});

const mapTabContainer = (properties: TabContainerProps & Variant) => ({
  'data-outlined': properties.outlined ?? false,
  'data-variant': properties.variant ?? 'secondary',
});
```

2021-06-07 10:49 UTC, sergeysova commented on src/ui/molecules/tabs/usage.mdx
> +    <TabContainer variant="primary">
Чет с неймингом странное;
Если это контейнер, почему его не назвать просто `Tabs`?

2021-06-07 10:49 UTC, sergeysova commented on src/ui/molecules/tabs/usage.mdx
> +        <TabList
Если это TabList, то он должен содержать или отображать список табов, но этот компонент представляет собой единственный таб.

Мб лучше назвать его `Tab` ?

2021-06-07 13:21 UTC, purplecandle commented on src/ui/molecules/tabs/usage.mdx
> +        <TabList
По мне, `Tab` – это компонент, который содержит в себе список табов и список панелек с контентом. `TabList` возможно будет уместно, если дальше будет такое расширение функционала

2021-06-07 13:23 UTC, purplecandle commented on src/ui/molecules/tabs/index.tsx
> +});
Согласен 👆🏻

2021-06-07 13:54 UTC, purplecandle requested changes
В целом хорошо 👍

2021-06-07 13:54 UTC, purplecandle commented on src/ui/molecules/tabs/usage.mdx
> +| `iconLeft`  | `React.ReactNode`                  |               | Left icon                           |
может стоило еще пример с `iconLeft`

2021-06-07 13:54 UTC, purplecandle commented on src/ui/molecules/tabs/index.tsx
> +  min-width: 201px;
в чем смысл? по сути это означает просто `width: 201px`

2021-06-07 13:54 UTC, purplecandle commented on src/ui/molecules/tabs/index.tsx
> +    <div data-content data-active={active}>
удалить `data-active={active}`, сделать пропом `active={active}` у родителя `TabItemContainer`. Наверное, так и хотела, сейчас `active` состояние из-за этого не работает

2021-06-07 13:54 UTC, purplecandle commented on src/ui/molecules/tabs/index.tsx
> +      width: 45%; /* 1 */
к чему комментарий?

2021-06-07 13:54 UTC, purplecandle commented on src/ui/molecules/tabs/index.tsx
> +      <span data-link="link-text">{text}</span>
текст внутри таба можно выделять

2021-06-07 19:12 UTC, purplecandle commented on src/ui/molecules/tabs/index.tsx
> +    <div data-content data-active={active}>
```suggestion
    variant={variant}
    active={active}
  >
    <div data-content>
```

2021-06-08 11:04 UTC, tatinacher requested changes
Табы топ надо ток чуть поправить

2021-06-08 11:04 UTC, tatinacher commented on src/ui/molecules/tabs/usage.mdx
> +    active: false
Можно еще пример с иконками

2021-06-08 11:04 UTC, tatinacher commented on src/ui/molecules/tabs/usage.mdx
> +| `outlined`  | `boolean`                          | `false`       | Add outlened variant                |
Add **outlened**

2021-06-10 15:07 UTC, Irinaristova commented on src/ui/molecules/tabs/index.tsx
> +  <TabItemContainer
+

2021-06-11 10:10 UTC, purplecandle approved these changes

2021-06-11 10:10 UTC, purplecandle commented on src/ui/molecules/tabs/usage.mdx
> +Tab can consist icon on left side ex. icon, logo or avatar
```suggestion
Tab can have an icon on the left side ex. icon, logo or avatar
```

2021-06-11 10:33 UTC, rchubarkin commented on src/ui/molecules/tabs/usage.mdx
> +          href={`#${id}`}
а как дальше планируется юзать этот href ?

2021-06-11 13:39 UTC, Irinaristova commented on src/ui/molecules/tabs/usage.mdx
> +          href={`#${id}`}
возможно будет переход по ссылке на другую страницу, договаривались делать табы по примеру браузерных, поэтому и добавила href

2021-06-16 15:50 UTC, tatinacher commented
<img width="570" alt="Снимок экрана 2021-06-16 в 18 47 59" src="https://user-images.githubusercontent.com/28189463/122251705-6e5de280-ced3-11eb-999b-d6a3a0b2e307.png">

Немного странно что у маленького тултипа исчезает буква в конце, хотя места достаточно

2021-06-16 15:51 UTC, tatinacher commented
<img width="875" alt="Снимок экрана 2021-06-16 в 18 51 24" src="https://user-images.githubusercontent.com/28189463/122252248-dca2a500-ced3-11eb-9bbd-090d829c682f.png">

Немного не совпадает с макетом

2021-06-16 16:01 UTC, tatinacher requested changes

2021-06-17 10:43 UTC, sergeysova commented on src/ui/molecules/tabs/index.tsx
> +export const Tabs = styled.div.attrs(mapTabs)`
Тогда будет сложно реализовать всякие клики и сложную работу с табами

2021-06-17 10:51 UTC, sergeysova approved these changes

2021-06-22 08:36 UTC, sergeysova commented
@Irinaristova порешаешь конфликты?

2021-06-24 08:48 UTC, sergeysova requested changes

2021-06-24 08:48 UTC, sergeysova commented on src/woly/molecules/tabs/index.tsx
> +  const ref = React.useRef<HTMLDivElement>(null);
Не вижу, чтобы реф как-то использовался

2021-08-02 14:50 UTC, purplecandle commented on src/woly/molecules/tabs/index.tsx
> +      {iconLeft && <span data-icon="link-icon">{iconLeft}</span>}
```suggestion
      {iconLeft && <span data-element="link-icon">{iconLeft}</span>}
```
**suggestion(blocking):** Новая форма дата-атрибутов

2021-08-05 18:05 UTC, rchubarkin approved these changes

2021-08-06 09:10 UTC, purplecandle approved these changes

2021-08-06 09:20 UTC, merged