[FRNT-507] Implement data table
woly-ui/woly pull request #124
Opened 2021-05-27 16:04 UTC by tatinacher

Implement data table
- FRNT-507

2021-05-28 10:53 UTC, Irinaristova commented on src/ui/molecules/data-table/filter.tsx
> +      <FilterButton onClick={setOpen}>
а почему нельзя кнопку переиспользовать ?

2021-05-28 10:53 UTC, Irinaristova commented on src/ui/molecules/data-table/filter.tsx
> +      <ListContainer style={{ display: isOpen ? 'block' : 'none' }}>
сюда наверное нужен popover, он покроет эти нужды и не нужно будет использовать инлайновые стили

2021-05-28 10:53 UTC, Irinaristova commented on src/ui/molecules/data-table/filter.tsx
> +    <FilterBlock>
разве блок не должен принимать пропс onChange, который будет прилетать сверху и фильтровать всю таблицу ?

2021-05-28 10:53 UTC, Irinaristova commented on src/ui/molecules/data-table/filter.tsx
> +          <Button variant="primary" outlined text="Применить" />
мб сюда просто передавать children? у тебя ж может не быть этой кнопки совсем или кнопка может быть другая, а у тебя тут уже зашито внутрь

2021-05-28 10:53 UTC, Irinaristova commented on src/ui/molecules/data-table/index.tsx
> +  emptyValue: string;
а почему именно такое название, но по итогу там все-таки лежит "---" ?

2021-05-31 08:35 UTC, tatinacher commented on src/ui/molecules/data-table/filter.tsx
> +      <FilterButton onClick={setOpen}>
Filter не входит в компонент, просто написала для примера какой может быть фильтр.

2021-05-31 08:56 UTC, tatinacher commented on src/ui/molecules/data-table/filter.tsx
> +      <ListContainer style={{ display: isOpen ? 'block' : 'none' }}>
+

2021-05-31 08:56 UTC, tatinacher commented on src/ui/molecules/data-table/filter.tsx
> +    <FilterBlock>
Не писала сам фильтр, не было такой задачи

2021-05-31 08:59 UTC, tatinacher commented on src/ui/molecules/data-table/filter.tsx
> +          <Button variant="primary" outlined text="Применить" />
Filter это визуальный пример, чтобы показать ,что мы можем в заголовок передать компонент фильтр, в дальнейшем нужно будет заменить на реализованный компонент Filter

2021-05-31 09:03 UTC, tatinacher commented on src/ui/molecules/data-table/index.tsx
> +  emptyValue: string;
Для ячеек без значений в макете выводится "----",  Саша Ш. не прорабатывал этот момент.
Реализовала этот пропс, чтобы можно было сверху передать, что показывать при пустой ячейке, и оставила по дефолту "----". Возможно нейминг пропса не оч, есть предложения как назвать лучше? мб emptyCellPlaceholder?

2021-05-31 09:48 UTC, Irinaristova commented on src/ui/molecules/data-table/filter.tsx
> +    <FilterBlock>
в задаче немного другой пример описал Серега и там как раз прокидывается и onChange, и state  - https://liberty-base.atlassian.net/browse/FRNT-507?atlOrigin=eyJpIjoiNDRmN2VjNzcyODFmNDdhN2I3MzMzY2FkOWNhMjNiZTIiLCJwIjoiaiJ9

2021-06-07 10:51 UTC, sergeysova commented on src/ui/molecules/data-table/index.tsx
> +  emptyValue: string;
`emptyPlaceholder` || `placeholder`

Можно в этом направлении попробовать)

2021-06-07 10:54 UTC, sergeysova requested changes

2021-06-07 10:54 UTC, sergeysova commented on src/ui/molecules/data-table/usage.mdx
> +    value: 'МИР'
Кажется, тут перепутаны value и name.
name это то, что видит пользователь, value это внутреннее значение, например, передаваемое на бекенд

2021-06-07 10:54 UTC, sergeysova commented on src/ui/molecules/data-table/usage.mdx
> +    title:  <Filter title="Название банка" data={bankNames}/>,
```suggestion
    title:  <Filter title="Название банка" options={bankNames}/>,
```

Кажется, это будет более прозрачно, если назвать опции, вместо абстрактного data

2021-06-07 14:41 UTC, purplecandle reviewed
Посмотрю, как будет сделана фильтрация

2021-06-08 10:40 UTC, tatinacher commented
> Посмотрю, как будет сделана фильтрация

В задаче нужно было сделать только DataTable без компонента фильтрации, в дальнейшем как реализуем сам компонент можно будет заменить заглушку Filter.

2021-06-16 11:20 UTC, rchubarkin commented on src/ui/molecules/data-table/index.tsx
> +interface ColumnProps {
В описании задачи не такой api, там что-то вроде. Чтобы можно было задать кастомный рендер ячейке и заголовку
```
interface ColumnProps {
  property: string;
  head: React.ReactNode | string  | ((props: HeadProps) => React.ReactNode);
  cell?: (props: CellProps) => React.ReactNode;
}
```

Еще имхо семантичнее назвать просто Column, потому что это не пропсы компонента

2021-06-16 11:20 UTC, rchubarkin commented on src/ui/molecules/data-table/index.tsx
> +interface DataTableProps {
Тут было бы очень круто сделать пропсы с дженериком

2021-06-16 16:24 UTC, tatinacher commented on src/ui/molecules/data-table/index.tsx
> +interface ColumnProps {
Была задача сделать таблицу, где для столбца в шапку таблицы можно передать компонент для фильтрации этого столбца. Проп property отвечает за сопоставление колонки и данных в таблице, title же по выбору обычная строка для заголовка колонки или сам компонент фильтрации. 

Не совсем поняла зачем еще передавать проп cell в шапку столбца?

2021-06-16 16:26 UTC, tatinacher commented on src/ui/molecules/data-table/index.tsx
> +interface DataTableProps {
Для values? В принципе можно

2021-06-16 19:33 UTC, rchubarkin commented on src/ui/molecules/data-table/index.tsx
> +interface ColumnProps {
кастомный рендер для ячейки
например тебе нужно собрать ссылку из данных в ячейке или сделать дропдаун с экшенами в таблице или форматировать сырую дату в таблице. Сейчас все что можно это поле по ключу достать

2021-06-17 09:01 UTC, tatinacher commented on src/ui/molecules/data-table/index.tsx
> +interface ColumnProps {
У меня сейчас за поле по ключу отвечает просп property, а за рендер ячейки колонки title

2021-06-17 14:23 UTC, sergeysova submitted a review, later dismissed

2021-06-17 14:23 UTC, sergeysova commented on src/ui/molecules/data-table/index.tsx
> +          ))}
```suggestion
          {columns.map(({ property, cell }) => {
          	const Cell = isComponent(cell) ? cell : CellContentDefault;
          	return (
            	<Td key={property}>
            		<Cell
            			property={property}
          				value={row[property]}
          				placeholder={placeholder}
      				/>
            	</Td>
          	)
          })}
```

А здесь тогда тоже можно будет создать свой рендерер

2021-06-21 14:55 UTC, tatinacher commented on src/ui/molecules/data-table/usage.mdx
> +
а в какой версии? в последней выпущенной вроде все по старому

2021-07-06 10:27 UTC, Irinaristova commented on src/woly/atoms/table/index.tsx
> +  color: var(--woly-neutral);
тут может быть любой цвет в зависимости от priority

2021-07-06 10:27 UTC, Irinaristova commented on src/woly/atoms/table/index.tsx
>    padding: var(--local-vertical) var(--local-horizontal);
дважды паддинги написаны

2021-07-06 10:27 UTC, Irinaristova commented on src/woly/molecules/data-table/filter.tsx
> +  <span>
мб тут лучше семантичные теги использовать, а не span

2021-07-06 10:27 UTC, Irinaristova commented on src/woly/molecules/data-table/filter.tsx
> +    from {value.from || placeholder} to {value.to || placeholder}
сейчас нет возможности стилизовать текст внутри

2021-07-15 11:00 UTC, risenforces commented on src/woly/atoms/table/index.tsx
> +  color: var(--woly-neutral);
Не очень понятно, относится ли это к data-table, ведь код из обычного table

2021-07-15 11:01 UTC, risenforces commented on src/woly/atoms/table/index.tsx
>    padding: var(--local-vertical) var(--local-horizontal);
Аналогично обсуждению выше

2021-07-15 11:01 UTC, risenforces commented on src/woly/molecules/data-table/filter.tsx
> +  <span>
> мб тут лучше семантичные теги использовать, а не span

Это же содержимое ячейки, там должен быть инлайн-текст, нет?

2021-07-15 14:17 UTC, risenforces commented on src/woly/molecules/data-table/filter.tsx
> +    from {value.from || placeholder} to {value.to || placeholder}
RangeCell это кастомный элемент для примера

2021-07-15 14:22 UTC, risenforces commented
- Добавил поле `head` для рендера кастомной ячейки в шапке, принимает `title` в пропсах
- Добавил `rowKey` для возможности указать кастомное поле для `key`
- Добавил возможность менять `placeholder` также на уровне `column`
- Реэкспорт типов

Хотелось бы пример с рабочими фильтрами запилить, но эффектор что-то не работает в доке (видимо из-за сср), а с контекстами много мучиться придется, и опять же небольшая проблема с тем, что в Playground только jsx попадает, так бы было проще написать пример

2021-07-15 14:23 UTC, risenforces commented
Сейчас вроде бы все соответствует примеру в jira, гляньте

2021-07-15 14:26 UTC, risenforces commented on src/woly/atoms/table/index.tsx
> +  color: var(--woly-neutral);
А, хотя, это изменение из этого пра, понял) Актуально же еще?

2021-07-15 14:27 UTC, risenforces commented on src/woly/molecules/data-table/usage-helpers.tsx
> +      <Filter value={[]} onChange={() => {}} options={bankNames} title={title} />
Фильтры очень сложно рабочими сделать, ограничивается тем, что эффектор в доке не заводится, ну а с контекстами очень неприятно будет

2021-07-19 10:49 UTC, Irinaristova commented on src/woly/atoms/table/index.tsx
> +  color: var(--woly-neutral);
question (blocking): Актуально, цвет заливки должен меняться в зависимости от палитры

2021-07-19 10:49 UTC, Irinaristova commented on src/woly/atoms/table/index.tsx
>    padding: var(--local-vertical) var(--local-horizontal);
suggestion: очень похоже на box, мб его сюда и стоит добавить?

2021-07-19 10:49 UTC, Irinaristova commented on src/woly/molecules/data-table/filter.tsx
> +      // remove
suggestion: мб стоит писать более развернутые комментарии и по формату, который приняли

2021-07-19 10:49 UTC, Irinaristova commented on src/woly/molecules/data-table/usage.mdx
> +    <DataTable rowKey="id" columns={columns} values={values} variant="primary" />
suggestion: variant не используем, это старый пропс, сейчас используем priority

2021-07-19 13:28 UTC, purplecandle commented on src/woly/molecules/data-table/index.tsx
> +          const padding = isReactEntity(title) ? '0' : '';
```suggestion
          const padding = React.isValidElement(title) ? '0' : '';
```
**question(blocking)**: почему бы не использовать встроенную в React проверку?

2021-07-19 13:28 UTC, purplecandle commented on src/woly/molecules/data-table/index.tsx
> +                  <Cell value={row[column.property]} placeholder={finalPlaceholder} />
```suggestion
                  <Cell value={row[column.property]} placeholder={column.placeholder || placeholder} />
```
**suggestion(non-blocking):** думаю, можно не создавать лишнюю переменную и мучаться с выбором имени

2021-07-19 13:28 UTC, purplecandle commented on src/woly/molecules/data-table/filter.tsx
> +import { IconArrowDown } from '../../../static/icons';
```suggestion
import { IconArrowDown } from 'static/icons';
```

2021-07-19 13:28 UTC, purplecandle commented on src/woly/molecules/data-table/filter.tsx
> +import { box } from '../../elements/box';
```suggestion
import { box } from 'ui/elements/box';
```

2021-07-19 13:39 UTC, risenforces commented on src/woly/molecules/data-table/index.tsx
> +          const padding = isReactEntity(title) ? '0' : '';
1) Проверка не только на элемент, но и на компонент
2) Типы isValidElement несовместимы с title

2021-07-19 14:02 UTC, risenforces commented on src/woly/molecules/data-table/index.tsx
> +                  <Cell value={row[column.property]} placeholder={finalPlaceholder} />
В принципе логично, обновил

2021-07-19 14:20 UTC, risenforces commented on src/woly/atoms/table/index.tsx
>    padding: var(--local-vertical) var(--local-horizontal);
box применяет padding на детей - а в ячейках таблицы нет элементов, только текстовые ноды

Есть предложения как решить?

2021-07-19 14:22 UTC, Irinaristova commented on src/woly/atoms/table/index.tsx
>    padding: var(--local-vertical) var(--local-horizontal);
Надо с Димой поговорить, как вариант: оборачивать в компонент текст

2021-07-19 14:32 UTC, risenforces commented on src/woly/atoms/table/index.tsx
>    padding: var(--local-vertical) var(--local-horizontal);
Тут на самом деле проблемы есть, довольно большие

Если скрытно оборачивать в Text - при передаче кастомной ячейки это либо тоже надо делать как-то (возможно разбивать ячейку на 2 компонента), либо перекладывать ответственность на юзера, которому придется держать в голове что паддингов никаких не будет, и надо обернуть текст во что-то

2021-07-19 14:33 UTC, risenforces commented on src/woly/atoms/table/index.tsx
>    padding: var(--local-vertical) var(--local-horizontal);
Ну и сам подход со скрытным оборачиванием и оберткой ради обертки - не оч хорошо как по мне, тем более такое ощущение, что текст предназначен для полноценных параграфов, а тут небольшой контент внутри ячейки, который как бы не совсем то же самое

2021-07-19 14:50 UTC, Irinaristova commented on src/woly/atoms/table/index.tsx
>    padding: var(--local-vertical) var(--local-horizontal);
Контент может быть разный, например, название продуктов будет или комментарий - кейс, когда контента достаточно много

2021-07-19 14:57 UTC, Irinaristova commented on src/woly/atoms/table/index.tsx
>    padding: var(--local-vertical) var(--local-horizontal);
Со скрытым оборачиванием согласна не очень подход, но можно компонент текст зашить внутрь, тогда у него будет и дефолтное значение, и можно будет кастомизировать + семантика будет поддерживаться, что думаешь?

2021-07-19 14:58 UTC, risenforces commented on src/woly/molecules/data-table/usage.mdx
> +    <DataTable rowKey="id" columns={columns} values={values} variant="primary" />
Поправил

P.S. это наверное **nitpick(blocking)**

2021-07-19 15:10 UTC, risenforces commented on src/woly/atoms/table/index.tsx
>    padding: var(--local-vertical) var(--local-horizontal);
> Со скрытым оборачиванием согласна не очень подход, но можно компонент текст зашить внутрь, тогда у него будет и дефолтное значение, и можно будет кастомизировать + семантика будет поддерживаться, что думаешь?

Смотри какая проблема вылезает:

В компоненте `Cell` в пропсах приходит `value`, это исходное значение, там может быть и объект (например range, как в usage)

Его нельзя обернуть в `Text`, т.к. сначала надо преобразовать в строку
И выходит что в 1 этап такое не сделать с зашитым текстом

Надо либо разбить на несколько этапов:
1) Преобразование значения в строку (на стороне юзера)
2) Оборачивание строки в Text (скрыто в DataTable)
3) Получение значения в `CustomCell` через пропсы в виде `children` и его рендер (на стороне юзера)

Если убирать любой из этапов, вылезут другие проблемы:
Для 1 - не скрыть Text
Для 2 - проблема с padding
Для 3 - юзер может вместо строки рендерить что-то другое, например список, и этот список будет автоматом оборачиваться в Text, что некорректно

2021-07-19 15:13 UTC, risenforces commented on src/woly/atoms/table/index.tsx
>    padding: var(--local-vertical) var(--local-horizontal);
Разве что думаю решаемо через React.children - можно посмотреть результат Cell, и если там нет никакой обертки (просто фрагмент или строка) - оборачивать в Text

2021-07-20 09:39 UTC, risenforces commented on src/woly/atoms/table/index.tsx
> +  color: var(--woly-neutral);
А можешь пояснить, как вообще должно быть? Насколько я вижу, ни один цвет из палитры не подходит на фон, ни canvas (он прозрачный), ни тем более shape. А соответствующие цвета для текста (canvas-text, shape-text) предназначены как раз под соответствующий фон. Выходит что ничего не сочетается.

2021-08-09 13:12 UTC, risenforces commented on src/woly/atoms/table/index.tsx
> +  color: var(--woly-neutral);
@Irinaristova глянь, сейчас норм?

2021-08-09 13:12 UTC, risenforces commented on src/woly/molecules/data-table/filter.tsx
> +  <span>
@Irinaristova RangeCell это как бы пример того, что будет на проекте, он не включен в экспорты

2021-08-09 13:13 UTC, risenforces commented on src/woly/atoms/table/index.tsx
>    padding: var(--local-vertical) var(--local-horizontal);
**Решили сделать в отдельной задаче после готовности новых боксов**

2021-08-09 13:14 UTC, risenforces commented on src/woly/molecules/data-table/filter.tsx
> +      // remove
@Irinaristova Кажется это касается только комментов вроде `TODO`, для которых важна дата, нет?

2021-08-09 15:05 UTC, purplecandle commented on src/woly/molecules/data-table/usage.mdx
> +    value: 'Альфа',
```suggestion
    value: 'Альфа'-банк,
```
**suggestion:** В **values** используется это значение

2021-08-09 15:06 UTC, purplecandle submitted a review, later dismissed

2021-08-09 15:13 UTC, Irinaristova submitted a review, later dismissed

2021-08-09 15:14 UTC, purplecandle approved these changes

2021-08-09 15:15 UTC, Irinaristova approved these changes

2021-08-09 15:19 UTC, merged