FRNT-530: add global styles, add wb variant
woly-ui/woly pull request #127
Opened 2021-06-01 13:54 UTC by Irinaristova

2021-06-07 12:24 UTC, sergeysova requested changes

2021-06-07 12:24 UTC, sergeysova commented on src/lib/global.ts
> +  --grey-darker-9: 240, 7%, 11%;
```suggestion
  --grey-0: 0, 0%, 0%;
  --grey-100: 249, 7%, 81%;
  --grey-200: 240, 7%, 92%;
  --grey-300: 240, 9%, 98%;
  --grey-400: 245, 6%, 66%;
  --grey-500: 247, 7%, 48%;
  --grey-600: 248, 7%, 40%;
  --grey-700: 251, 7%, 30%;
  --grey-800: 249, 7%, 21%;
  --grey-900: 240, 7%, 11%;
  --grey-1000: 0, 0%, 100%;
```

Это палитра black-white, в темной теме, все значения инвертируются и получится, что в переменной `base-black` будет лежать белый цвет, что крайне не логично и будет ломать всю концепцию абстрактных имен.

в случае `grey-0` это не яркость а насыщенность цвета. Но в какую сторону насыщенность решает тема, а не название цвета

2021-06-07 12:24 UTC, sergeysova commented on src/lib/global.ts
> +  --brand-color-darker-9: 256, 61%, 13%;
Почему brand?

Он же primary цвет. Будет ещё и secondary

2021-06-07 12:24 UTC, sergeysova commented on src/ui/atoms/input/usage.mdx
> +      variant="white-and-black"
```suggestion
      variant="default"
```

Так, нет же палитры `white-and-black`

2021-06-07 15:39 UTC, purplecandle approved these changes

2021-06-07 15:40 UTC, purplecandle requested changes
После исправления замечаний @sergeysova

2021-06-08 09:25 UTC, tatinacher requested changes
А где примеры с -on-color?

2021-06-08 13:54 UTC, tatinacher requested changes

2021-06-08 13:54 UTC, tatinacher commented on src/lib/global.ts
> +  /* dagner palette */
dagner 😉

2021-06-08 13:54 UTC, tatinacher commented on src/lib/global.ts
> +  --base-danger-color: 356, 100%, 78%;
не используется

2021-06-08 13:54 UTC, tatinacher commented on src/ui/atoms/button/index.tsx
> +  fullWidth?: boolean;
Надо бы добавить в табличку с пропсами в доке

2021-06-08 13:54 UTC, tatinacher commented on src/ui/atoms/button/index.tsx
>    outlined?: boolean;
и outlined тоже

2021-06-09 12:58 UTC, purplecandle approved these changes
Все хорошо 😊

2021-06-09 14:44 UTC, tatinacher approved these changes

2021-06-15 08:19 UTC, sergeysova approved these changes

2021-06-15 08:21 UTC, merged