feat: implement loader component
woly-ui/woly pull request #130
Opened 2021-06-03 15:57 UTC by purplecandle

Информация от дизайнера:

- все размеры фиксированные
- ограничения на количество строк текста нет

2021-06-07 12:28 UTC, sergeysova approved these changes

2021-06-07 15:04 UTC, Irinaristova commented on src/ui/atoms/loader/usage.mdx
> +| `variant`     | `string`         | `'primary'`  | Variant prop to style Input component           |
loader

2021-06-07 15:04 UTC, Irinaristova commented on src/ui/atoms/loader/index.tsx
> +    line-height: 21px;
ты строчкой выше уже определил line-height, но лучше просто в примере использовать компонент Text

2021-06-07 15:04 UTC, Irinaristova commented on src/ui/atoms/loader/usage.mdx
> +`Loader` component is used when retrieving data or performing slow computations, and help to notify users that loading is underway..
лишняя точка в конце предложения

2021-06-07 15:04 UTC, Irinaristova commented on src/ui/atoms/loader/index.tsx
> +    font-weight: 400;
есть компонент text, лучше тогда его использовать в примере, кажется здесь не нужно харкодить font-weight

2021-06-07 15:04 UTC, Irinaristova commented on src/ui/atoms/loader/index.tsx
> +    margin-bottom: calc(var(--local-gap) * 2);
откуда появился local-gap? ты ж его выше не объявляешь

2021-06-07 15:04 UTC, Irinaristova commented on src/ui/atoms/loader/index.tsx
> +  --local-size: calc(
размер loader разве не будет фиксированным?

2021-06-07 15:04 UTC, Irinaristova commented on src/ui/atoms/loader/index.tsx
> +        <svg viewBox="0 0 100 100" data-track>
почему не положить svg в src/static/icons, а сюда импортировать?

2021-06-07 15:04 UTC, Irinaristova commented on src/ui/atoms/loader/index.tsx
> +    1px * var(--woly-component-level) * var(--woly-main-level) * 4
откуда появилась цифра 4? в дизайн системе все значения кратны 3, если не получается использовать значение кратное 3, то лучше вынести 4 в локальную переменную

2021-06-07 18:19 UTC, Irinaristova commented on src/ui/atoms/loader/index.tsx
> +  variant = 'primary',
дефолтный вариант secondary пока что

2021-06-07 18:19 UTC, Irinaristova commented on src/ui/atoms/loader/usage.mdx
> +<Playground>
можно сделать пример с кнопкой, при клике на которую запускается спиннер
но можно сделать и более сложный пример

2021-06-07 18:19 UTC, Irinaristova commented on src/ui/atoms/loader/usage.mdx
> +| `variant`     | `string`         | `'primary'`  | Variant prop to style Input component           |
secondary

2021-06-07 18:19 UTC, Irinaristova commented on src/ui/atoms/loader/index.tsx
> +  description?: string;
сюда лучше передавать string | React.ReactNode, потому что сам текст чаще всего будет обернут в компонент Text для стилизации

2021-06-07 18:19 UTC, Irinaristova commented on src/ui/atoms/loader/index.tsx
> +        <div data-text>{description}</div>
тогда мб стоит и дата атрибут также назвать?

2021-06-07 18:19 UTC, Irinaristova commented on src/ui/atoms/loader/index.tsx
> +  --local-size: calc(
лучше переменную назвать --local-track-size, что сразу понимать что туда записано, сейчас название очень обобщенное

2021-06-08 07:05 UTC, purplecandle commented on src/ui/atoms/loader/index.tsx
> +    font-weight: 400;
Тогда это уже не будет сможет быть атомом и придется его перемещать его вверх по иерархии. @sergeysova  @tatinacher что скажите?

2021-06-08 07:17 UTC, purplecandle commented on src/ui/atoms/loader/index.tsx
> +    1px * var(--woly-component-level) * var(--woly-main-level) * 4
> откуда появилась цифра 4? в дизайн системе все значения кратны 3, если не получается использовать значение кратное 3, то лучше вынести 4 в локальную переменную

Нужно бы все эти нюансы вынести в README. @sergeysova можем потом этим позаботиться?

2021-06-08 07:30 UTC, purplecandle commented on src/ui/atoms/loader/index.tsx
> +    margin-bottom: calc(var(--local-gap) * 2);
из box

2021-06-08 07:48 UTC, purplecandle commented on src/ui/atoms/loader/index.tsx
> +  description?: string;
React.ReactNode – слишком широкий тип, я бы использовал React.ReactChild

2021-06-08 08:49 UTC, purplecandle commented on src/ui/atoms/loader/index.tsx
> +    font-weight: 400;
окей, я понял как лучше сделать

2021-06-08 10:02 UTC, tatinacher approved these changes

2021-06-08 10:02 UTC, tatinacher commented on src/ui/atoms/loader/usage.mdx
> +      <React.Fragment>
Тут тоже можно заменить на <></>

2021-06-16 16:10 UTC, tatinacher submitted a review, later dismissed
Крутые примеры 👍

2021-06-17 10:53 UTC, sergeysova requested changes

2021-06-17 10:53 UTC, sergeysova commented on src/ui/atoms/loader/usage.mdx
> +  <ExampleDataFetching />
Лучше разместить большую часть кода в этом файле, иначе в превью выглядит как затычка, непонятно как оно устроено.
Придется лезть в исходники в repo

2021-06-18 17:31 UTC, Irinaristova approved these changes

2021-06-18 17:31 UTC, Irinaristova commented on src/ui/atoms/loader/index.tsx
> +  description = 'Loading...',
мб отсортировать?

2021-06-19 18:53 UTC, Irinaristova approved these changes

2021-06-21 09:43 UTC, sergeysova approved these changes

2021-06-21 09:43 UTC, merged