[FRNT-501] add spec for button
woly-ui/woly pull request #132
Opened 2021-06-07 10:19 UTC by Irinaristova

2021-06-07 12:13 UTC, sergeysova requested changes
Описано очень круто, я докинул лишь пометки о нескольких неточностях

2021-06-07 12:13 UTC, sergeysova commented on src/ui/atoms/button/button-spec.mdx
> +В основном выделяют 3 часто используемых размера для кнопокё:
```suggestion
В основном выделяют 3 часто используемых размера для кнопок:
```

2021-06-07 12:13 UTC, sergeysova commented on src/ui/atoms/button/button-spec.mdx
> +Плохо, если нужно прочитать все содержимое лайтбокса, чтобы понять, что делает кнопка.
```suggestion
Плохо, если нужно прочитать все содержимое лайтбокса или тултипа, чтобы понять, что делает кнопка.
```

2021-06-07 12:13 UTC, sergeysova commented on src/ui/atoms/button/button-spec.mdx
> +  Действие происходит после того, как кнопка отпущена, и только в том случае, если курсор остался над кнопкой.
Было бы круто добавить несколько пунктов про фокусировку и взаимодействие с клавиатурой (space or enter)

2021-06-07 12:13 UTC, sergeysova commented on src/ui/atoms/button/button-spec.mdx
> +Фокус на кнопке визуально отображается только при работе с клавиатурой: если перенести на неё фокус табом появляется рамка или тень (в браузерах по умолчанию используется рамка синего цвета).
Фокус также отображается после клика на кнопке
или после нажатия курсором, но отпускании уже за границами кнопки

2021-06-07 15:47 UTC, purplecandle requested changes

2021-06-07 15:47 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +  Действие происходит после того, как кнопка отпущена, и только в том случае, если курсор остался над кнопкой.
Еще бы добавить про disabled состояние

2021-06-07 15:47 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +Основное правило - оформление должно быть однотипным по всему проекту.
Можешь дополнить, слишком кратко

2021-06-07 15:47 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +-маленькие — используйте рядом с полям ввода или внутри них. Соответствуют по высоте с располагаемыми рядом элементами.
```suggestion
-маленькие — используйте рядом с полям ввода или внутри них. Соответствуют высоте с располагаемыми рядом элементами.
```

2021-06-07 16:42 UTC, Irinaristova commented on src/ui/atoms/button/button-spec.mdx
> +-маленькие — используйте рядом с полям ввода или внутри них. Соответствуют по высоте с располагаемыми рядом элементами.
тогда уж соответствуют высоте располагаемого рядом элемента )

2021-06-08 09:55 UTC, tatinacher approved these changes

2021-06-10 10:47 UTC, purplecandle requested changes
Есть мелкие ошибки

2021-06-10 10:47 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +- при нажатия на кнопку текст и иконка может опускаться на 1 px или менять цвет с добавлением рамки;
```suggestion
- при нажатии на кнопку текст и иконка может опускаться на 1 px или менять цвет с добавлением рамки;
```

2021-06-10 10:47 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +- фокус на кнопке визуально отображется после клика на кнопку, после нажатия курсором, но отпускании уже за границами кнопки, а также при работе с клавиатурой: если табом перенести фокус на кнопку по
```suggestion
- фокус на кнопке визуально отображается после клика на кнопку, после нажатия курсором, но отпускании уже за границами кнопки, а также при работе с клавиатурой: если табом перенести фокус на кнопку появляется рамка или тень (в браузерах по умолчанию используется рамка синего цвета).
```

2021-06-10 10:47 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +Oформление кнопок в проекте рекомендуется выполнять в едином стиле. Единство стиля улучшает скорость и точность взаимодействия, помогает избежать ошибок.
```suggestion
Оформление кнопок в проекте рекомендуется выполнять в едином стиле. Единство стиля улучшает скорость и точность взаимодействия, помогает избежать ошибок.
```

2021-06-10 10:47 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +Вместе с тем, пользователю необходимо отличать более важные действия от не таких важных.
```suggestion
Вместе с тем пользователю необходимо отличать более важные действия от не таких важных.
```

2021-06-10 10:47 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +В основнном на странице или в отдельном блоке обычно используют одную "основную" кнопку, а также несколько «второстепенных» и побочных, «третичных».
```suggestion
В основном на странице или в отдельном блоке обычно используют одну "основную" кнопку, а также несколько «второстепенных» и побочных, «третичных».
```

2021-06-10 10:47 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +  Соблюдайте иерархию кнопок - это напрвит пользователя совершить нужное действие быстрее.
```suggestion
  Соблюдайте иерархию кнопок - это направит пользователя совершить нужное действие быстрее.
```

2021-06-10 10:47 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +Используйте тень, чтобы придать кнопке "объем". При таком оформлениии кнопки более «кликабельны», поскольку затенение дает понять, что на кнопку можно нажать. Такие кнопки пользователи заметят быстре
```suggestion
Используйте тень, чтобы придать кнопке "объем". При таком оформлении кнопки более «кликабельны», поскольку затенение дает понять, что на кнопку можно нажать. Такие кнопки пользователи заметят быстрее, нежели плоские.
```

2021-06-10 10:47 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +В исключительных случаях, название кнопки формулируется от первого лица (когда действие касается непосредственно пользователя).
```suggestion
В исключительных случаях, название кнопки формулируется от первого лица, когда действие касается непосредственно пользователя.
```
возможно так лучше

2021-06-10 10:47 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +- маленькие — используются рядом с полям ввода или внутри них и соответствуют высоте располагаемого рядом элемента.
```suggestion
- маленькие — используются рядом с полями ввода или внутри них и соответствуют высоте располагаемого рядом элемента.
```

2021-06-10 10:47 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +Кнока может быть дополнена исконкой. В основном иконка располагается слева от текста кнопки.
```suggestion
Кнопка может быть дополнена иконкой. В основном иконка располагается слева от текста кнопки.
```

2021-06-11 08:54 UTC, purplecandle submitted a review, later dismissed

2021-06-16 15:20 UTC, tatinacher submitted a review, later dismissed

2021-06-17 14:31 UTC, sergeysova approved these changes

2021-06-17 14:33 UTC, merged