[FRNT-504] add spec for link
woly-ui/woly pull request #133
Opened 2021-06-07 10:34 UTC by Irinaristova

2021-06-07 12:19 UTC, sergeysova requested changes
@Irinaristova похоже, что ты случайно создала ветку от ветки с кнопкой. Попробуй сделать ветку заново, а коммит со спекой ссылки просто черрипикнуть в новую ветку и затем forcepush сюда ж, чтобы не пересоздавать ПР

2021-06-07 16:22 UTC, purplecandle requested changes
Нужно немного отполировать, в целом хорошо

2021-06-07 16:22 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +Несмотря на то, что ссылка также может запускать действие, отличие между ссылкой и кнопкой состоит в том, что она заметнее,
```suggestion
Несмотря на то, что ссылка также может запускать действие, отличие между ссылкой и кнопкой состоит в том, что кнопка заметнее,
```

2021-06-07 16:22 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +### Кнопке можно передавать URL-адрес, то есть сделать из кнопки ( <button> ) ссылку, однако, не рекомендуется превращать кнопку в навигационный элемент по следующим причинам:
```suggestion
### Почему не стоит делать из кнопки ссылку
Кнопке можно передавать URL-адрес, то есть сделать из кнопки ( <button> ) ссылку, однако не рекомендуется превращать кнопку в навигационный элемент по следующим причинам:
```

2021-06-07 16:22 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +Основное правило - оформление должно быть однотипным по всему проекту.
Слишком коротко, попробуй дополнить

2021-06-07 16:22 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +-маленькие — используйте рядом с полям ввода или внутри них. Соответствуют по высоте с располагаемыми рядом элементами.
```suggestion
-маленькие — используйте рядом с полям ввода или внутри них. Они соответствуют высоте с располагаемыми рядом элементами.
```

2021-06-07 16:22 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +Фокус на кнопке визуально отображается только при работе с клавиатурой: если перенести на неё фокус табом появляется рамка или тень (в браузерах по умолчанию используется рамка синего цвета).
```suggestion
Фокус на кнопке визуально отображается только при работе с клавиатурой: если перенести на неё фокус табом, то вокруг появляется рамка или тень (в браузерах по умолчанию используется рамка синего цвета).
```

2021-06-07 16:22 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +Если кнопка в фокусе, то при нажатии клавиши Enter она нажиматься и выполняет указанное действие.
```suggestion
Если кнопка в фокусе, то при нажатии клавиши Enter она нажимается и выполняет указанное действие.
```

2021-06-07 16:22 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +При клике мышью или тапом на тачскрине кнопка получает фокус, но визуально не отображает его.
После клика же фокус появляется, или я путаю?

2021-06-07 16:22 UTC, purplecandle commented on src/ui/atoms/link/link-spec.mdx
> +`Ссылка` (html тег `<a>` ) — это элемент навигации, то есть элемент, отвечающий за взаимосвязь разделов веб-ресурса (или разных ресурсов) между собой.
```suggestion
`Ссылка` (html тег `<a>` ) — это элемент навигации, отвечающий за взаимосвязь разделов веб-ресурса (или разных ресурсов) между собой.
```

2021-06-07 16:22 UTC, purplecandle commented on src/ui/atoms/link/link-spec.mdx
> +Ссылка не должна вести на ту же страницу, на которой она находится.
```suggestion
Ссылка не должна вести на текущую страницу.
```

2021-06-07 16:22 UTC, purplecandle commented on src/ui/atoms/link/link-spec.mdx
> +Такие ссылки бесполезны и только запутывают пользователя: кликнул, страница загрузилась и оказалось, что ты остался там же, где и был.
```suggestion
Такие ссылки бесполезны и только запутывают пользователя, поскольку после клика и перезагрузки страницы он остается на том же месте что был до перезагрузки.
```

2021-06-07 16:22 UTC, purplecandle commented on src/ui/atoms/link/link-spec.mdx
> +Не рекомендуется использовать в работе ссылку-кнопку, т.к. она не будет иметь корректного URL-адреса и при наведении курсора на ссылку-кнопку в окне браузера (внизу) выведется «javascript:;» или «Тек
Выглядит как-то инородно, тем более такие советы шли в начале документа. Может туда переместить?

2021-06-07 16:22 UTC, purplecandle commented on src/ui/atoms/link/link-spec.mdx
> +## Различия между кнопкой и ссылкой:
```suggestion
## Кнопка или ссылка – что лучше использовать?
```

2021-06-07 16:22 UTC, purplecandle commented on src/ui/atoms/link/link-spec.mdx
> +Если по клику на ссылку с иконкой запускается продолжительное действие, иконка должна превращаться в спиннер, и затем возвращаться в начальное состояние.
Эм. Это ведь скоуп кнопки? Ссылка лишь для навигации. Продолжительное действие лучше делать с кнопкой. @sergeysova @tatinacher поправьте, если заблуждаюсь

2021-06-07 16:32 UTC, Irinaristova commented on src/ui/atoms/button/button-spec.mdx
> +Основное правило - оформление должно быть однотипным по всему проекту.
что слишком коротко?  Описание или сам заголовок?

2021-06-07 16:33 UTC, Irinaristova commented on src/ui/atoms/link/link-spec.mdx
> +Ссылка не должна вести на ту же страницу, на которой она находится.
Мне первый вариант больше нравится

2021-06-07 16:34 UTC, Irinaristova commented on src/ui/atoms/link/link-spec.mdx
> +## Различия между кнопкой и ссылкой:
Не очень использовать вопросы в подзаголовке, я специально убрала вопросы (так было в черновом варианте)

2021-06-07 17:41 UTC, Irinaristova commented on src/ui/atoms/link/link-spec.mdx
> +Если по клику на ссылку с иконкой запускается продолжительное действие, иконка должна превращаться в спиннер, и затем возвращаться в начальное состояние.
Даже в figma, когда переходишь по ссылкам между страницами запускается спиннер. Здесь описано тоже самое действие, но спиннер отрисовывается не на основной странице по середине, а рядом с текстом ссылки

2021-06-07 19:39 UTC, purplecandle commented on src/ui/atoms/button/button-spec.mdx
> +Основное правило - оформление должно быть однотипным по всему проекту.
Описание

2021-06-07 19:42 UTC, purplecandle commented on src/ui/atoms/link/link-spec.mdx
> +## Различия между кнопкой и ссылкой:
Либо "Что лучше использовать: ссылки или кнопки"

2021-06-07 19:43 UTC, purplecandle commented on src/ui/atoms/link/link-spec.mdx
> +Если по клику на ссылку с иконкой запускается продолжительное действие, иконка должна превращаться в спиннер, и затем возвращаться в начальное состояние.
> Не согласна, ведь даже в figma, когда переходишь по ссылкам между страницами запускается спиннер. Здесь описано тоже самое действие, но спиннер отрисовывается не только на странице, куда перешел пользователь, но и рядом с текстом ссылки, например, когда у тебя боковое меню и много ссылок. Кнопка может запускать спиннер тоже, например, при отправке формы или загрузке таблицы с большим количеством данных.

ну возможно)

2021-06-08 09:51 UTC, tatinacher requested changes
Этот ПР ломает доку, потому что сейчас, если у mdx файла нет категории (как в спецификации), то выбрасывается Error.
Нужно либо временно прописать категорию файлу, либо временно заблокировать мерж ПР пока не доработаем тему

2021-06-08 09:51 UTC, tatinacher commented on src/ui/atoms/link/link-spec.mdx
> +Такие ссылки бесполезны и только запутывают пользователя: кликнул, страница загрузилась и оказалось, что ты остался там же, где и был.
Ссылки-якоря?

2021-06-08 09:51 UTC, tatinacher commented on src/ui/atoms/link/link-spec.mdx
> +Если по клику на ссылку с иконкой запускается продолжительное действие, иконка должна превращаться в спиннер, и затем возвращаться в начальное состояние.
Мне кажется при клике спиннер должен крутиться не возле ссылки, а в области загрузки

2021-06-11 08:49 UTC, purplecandle approved these changes

2021-06-16 15:23 UTC, tatinacher commented
Перевела в драфт, пока не смержим дубль этого ПР, потом этот ПР можно закрыть без мержа

2021-06-17 14:29 UTC, sergeysova commented on src/ui/atoms/button/button-spec.mdx
> +`Кнопка` (html тег `<button>` ) — это функциональный элемент, то есть элемент, отвечающий за выполнение определённой функции, действия.
Переименуй файл в `specification.mdx` плиз

2021-06-17 14:30 UTC, sergeysova commented on src/ui/atoms/link/link-spec.mdx
> +---
Аналогично и тут `specification.mdx` 

Не стоит дублировать имя компонента в имени файла

2021-06-17 14:30 UTC, sergeysova requested changes
&nbsp;

2021-06-18 15:36 UTC, closed without merging

2021-06-18 15:36 UTC, Irinaristova commented
via [FRNT-504]