[FRNT-542] Implement upload package
woly-ui/woly pull request #134
Opened 2021-06-08 09:11 UTC by tatinacher

Implement upload package
Implement Dropzone and UploadButton components, update UploadArea

2021-06-11 11:34 UTC, purplecandle commented on src/ui/atoms/button/usage.mdx
> +category: map
А для чего тут решили изменить имя и категорию?

2021-06-16 15:17 UTC, tatinacher commented on src/ui/atoms/button/usage.mdx
> +category: map
поправила

2021-06-17 14:38 UTC, sergeysova commented on build/builder.js
> +module.exports = { buildWoly, buildCalendar, buildUpload };
Стоит, но потом

2021-06-17 14:39 UTC, sergeysova commented on build/builder.js
> +module.exports = { buildWoly, buildCalendar, buildUpload };
Хм, ну раз уже сделали)

2021-06-17 14:59 UTC, sergeysova requested changes

2021-06-17 14:59 UTC, sergeysova commented on packages/woly/package.json
> +    "directory": "packages/upload"
```suggestion
    "directory": "packages/woly"
```

Это ж файл описания woly пакета

2021-06-17 14:59 UTC, sergeysova commented on src/upload/atoms/index.ts
> +export { UploadArea } from './upload-area';
Мне кажется это вообще не atom.

Мб organisms

2021-06-18 16:09 UTC, tatinacher commented on src/upload/atoms/index.ts
> +export { UploadArea } from './upload-area';
UploadArea используется в Dropzone, тогда не оч понятно на каком уровне будет Dropzone

2021-06-18 17:55 UTC, Irinaristova commented on src/upload/molecules/dropzone/index.tsx
> +  onDrop?: DropzoneOptions['onDrop'];
мб добавить 

multiple | bool | true | Allow drag 'n' drop (or selection from the file dialog) of multiple files - достаточно растпространенный кейс

2021-06-18 17:55 UTC, Irinaristova commented on src/upload/molecules/dropzone/index.tsx
> +  onDrop?: DropzoneOptions['onDrop'];
а валидацию файлов сами как-то будем настраивать? у дропзоны есть же пропс, добавлять не будем @sergeysova  ?

2021-06-18 17:55 UTC, Irinaristova commented on src/upload/molecules/dropzone/usage.mdx
> +| `variant`  | `string`                                                                                           | `'default'` | Variant prop to style UploadArea component
secondary

2021-06-18 17:55 UTC, Irinaristova commented on src/upload/molecules/dropzone/index.tsx
> +  const onFocus = React.useCallback(() => {
тут cb объявится 1 раз, в чем профит?

2021-06-18 17:55 UTC, Irinaristova commented on src/upload/atoms/upload-area/index.tsx
>    center?: boolean;
мб лучше назвать isPositionCenter ?

2021-06-21 08:41 UTC, tatinacher commented on src/upload/molecules/dropzone/index.tsx
> +  onDrop?: DropzoneOptions['onDrop'];
@Irinaristova Могу добавить, если нужно

2021-06-21 08:49 UTC, tatinacher commented on src/upload/atoms/upload-area/index.tsx
>    center?: boolean;
@Irinaristova мы вроде договорились все булеан переменные называть без приставки is (например outlined/disabled/visible)?

2021-06-21 10:08 UTC, Irinaristova commented on src/upload/atoms/upload-area/index.tsx
>    center?: boolean;
Тогда надо где-то это описать) но дата атрубут точно лучше переименовать data-position-center)

2021-06-21 14:38 UTC, tatinacher commented on src/upload/molecules/dropzone/index.tsx
> +  const onFocus = React.useCallback(() => {
можешь поподробнее расписать, не очень понятно, что имеешь ввиду

2021-06-22 08:34 UTC, sergeysova commented
@tatinacher порешаешь конфликты?

2021-07-06 09:01 UTC, rchubarkin requested changes

2021-07-07 13:37 UTC, rchubarkin approved these changes

2021-07-07 13:52 UTC, purplecandle commented on src/upload/elements/upload-area/index.tsx
> +    <div data-content data-position-center={center}>
Я не особо понял почему есть такая опция `data-position-center` если контейнер уже центрует контент через flex

2021-07-07 13:55 UTC, rchubarkin commented on src/upload/elements/upload-area/index.tsx
> +    <div data-content data-position-center={center}>
это я не заметил, принято

2021-07-07 13:58 UTC, purplecandle requested changes

2021-07-07 13:58 UTC, purplecandle commented on src/upload/molecules/upload-button/usage.mdx
> +        variant="primary"
```suggestion
        priority="primary"
```

2021-07-07 13:58 UTC, purplecandle commented on src/upload/molecules/upload-button/usage.mdx
> +        <UploadButton text="Upload files" icon={<IconPlus />} variant="primary" onChange={change} />
```suggestion
        <UploadButton text="Upload files" icon={<IconPlus />} priority="primary" onChange={change} />
```

2021-07-07 13:58 UTC, purplecandle commented on src/upload/molecules/upload-button/usage.mdx
> +| `text`      | `string`                                                         |               | Button text
А в типа React.ReactNode. Либо там, либо тут нужно исправить

2021-07-08 15:04 UTC, purplecandle submitted a review, later dismissed

2021-07-08 15:40 UTC, Irinaristova commented on packages/upload/package.json
> +    "react": "^16.11.0",
версия отстает

2021-07-08 15:40 UTC, Irinaristova commented on packages/woly/package.json
>      "react": "^16.11.0",
версия

2021-07-08 15:40 UTC, Irinaristova commented on src/upload/molecules/drag-uploader/usage.mdx
> +Drag and drop for files. Show dialog on drop file or upload area click
тут бы чуть больше описания работы uploader

2021-07-08 15:40 UTC, Irinaristova commented on src/upload/molecules/drag-uploader/usage.mdx
> +| `accept`    | `string ӏ string[]`                                                                                |               | File extensions that are accepted to load
multiple не хватает

2021-07-12 10:09 UTC, Irinaristova approved these changes

2021-07-12 10:50 UTC, purplecandle approved these changes

2021-07-12 11:24 UTC, sergeysova approved these changes

2021-07-12 11:24 UTC, merged