[FRNT-503] add chip specification
woly-ui/woly pull request #135
Opened 2021-06-11 10:39 UTC by Irinaristova

2021-06-11 11:00 UTC, rchubarkin approved these changes

2021-06-11 11:00 UTC, rchubarkin commented on src/ui/atoms/chip/chip-spec.mdx
> +Простой компонент чип, как правило, состоит из текста и иконка.
иконкИ

2021-06-11 13:24 UTC, purplecandle requested changes

2021-06-11 13:24 UTC, purplecandle commented on src/ui/atoms/chip/chip-spec.mdx
> +Чаще всего такие чипы используют при работе с мультиселекта. При этом, правая часть чипа в которой расположен экшен блок обычно отвечает за удаление чипа.
```suggestion
Чаще всего такие чипы используются для отображения выбранных значений мультиселекта. При этом правая часть чипа, в которой расположен экшен блок, обычно отвечает за удаление чипа.
```
Первое предложение была немного неясной для меня, перефразировал

2021-06-11 13:24 UTC, purplecandle commented on src/ui/atoms/chip/chip-spec.mdx
> +В составном чипе может быть кликабельной как только правая часть чипа с экшен блоком, так и одновременно с ней и левая часть, т.е. лейбл.
```suggestion
В составном чипе кликабельной может быть не только правая часть чипа с экшен блоком, но и весь чип.
```
Тоже немного перефразировал, чтобы повысить читаемость.

2021-06-11 13:24 UTC, purplecandle commented on src/ui/atoms/chip/chip-spec.mdx
> +При, это каждое состояние чипа должно иметь особенности, которые отличают его от других состояний и окружающего макета.
```suggestion
При этом каждое состояние чипа должно иметь особенности, которые отличают его от других состояний и окружающего макета.
```
typo

2021-06-11 13:24 UTC, purplecandle commented on src/ui/atoms/chip/chip-spec.mdx
> +Не рекомендуется кардинально изменять вид и создавать дополнительный визуальный шум нежелательно.
Не очень понятна вторая часть предложения, предлагаю перефразировать или дополнить

2021-06-11 13:24 UTC, purplecandle commented on src/ui/atoms/chip/chip-spec.mdx
> +Иконка должна соответствовать смыслу текста на чипе или действию, выполненного над чипом, иногда это позволяет пользователю понять назначение компонента до того, как он прочитал его название.
> действию, выполненного над чипом
действие над чипом или действие, которое совершает чип?

2021-06-16 11:14 UTC, purplecandle approved these changes

2021-06-16 11:39 UTC, tatinacher approved these changes
👍

2021-06-16 11:39 UTC, tatinacher commented on src/ui/atoms/chip/chip-spec.mdx
> +Чип может быть как простым компонентов, так и составным.
опечатка - компонентом

2021-06-16 11:39 UTC, tatinacher commented on src/ui/atoms/chip/chip-spec.mdx
> +При этом, сам компонент чип может быть как статичным, так и интерактивным (кликабельным).
Немножко орфографии -> запятая после "При этом" не нужна

2021-06-16 11:39 UTC, tatinacher commented on src/ui/atoms/chip/chip-spec.mdx
> +Чип может быть дополнен иконкой. В основном, иконка располагается слева от текста чипа, в редких случаях - справа.
"В основном" не нужно выделять запятыми на этой строке и ниже

2021-06-16 11:39 UTC, tatinacher commented on src/ui/atoms/chip/chip-spec.mdx
> +Так, к примеру, аватар, расположенный слева от текста чипа подскажет, что внутри лежат данные пользователя, а иконка-галочка справа от текста чипа обозначит, что информация из чипа добавлен пользоват
после "расположенный слева от текста чипа" запятая

2021-06-17 10:57 UTC, sergeysova commented on src/ui/atoms/chip/chip-spec.mdx
> +Чип может быть дополнен иконкой. В основном, иконка располагается слева от текста чипа, в редких случаях - справа.
В чипе не может быть иконки справа, только слева.
Иконка справа это всегда второстепенное действие с чипом

2021-06-17 11:04 UTC, sergeysova requested changes

2021-06-17 11:04 UTC, sergeysova commented on src/ui/atoms/chip/chip-spec.mdx
> +Составной компонент чип обычно состоит из двух частей: лейбла чипа - часть, в которой расположен только текст или текст с иконкой, а также экшен блока - часть, в которой отображается кнопка-иконка.
```suggestion
Составной компонент чип обычно состоит из двух частей: лейбл чипа - часть, в которой расположен только текст или текст с иконкой, а также экшен блока - часть, в которой отображается кнопка-иконка.
```

2021-06-21 09:42 UTC, sergeysova approved these changes

2021-06-21 09:42 UTC, merged