[FRNT-142] Integrate screenshot testing
woly-ui/woly pull request #140
Opened 2021-06-15 12:07 UTC by purplecandle

2021-06-15 14:39 UTC, Irinaristova commented on README.md
> +      // в этом случае будет 3 снапшота
в этом случае будет 3 снапшота, поскольку в массиве variant указано 3 значения

2021-06-15 14:39 UTC, Irinaristova commented on README.md
> +1. после PR в pipepline запускается отдельный job – собирается сборка с компонентами, затем поднимается сервер и запускается тест-раннер
порядок нумерации нужно поправить

2021-06-15 14:39 UTC, Irinaristova commented on README.md
> +1. после PR в pipepline запускается отдельный job – собирается сборка с компонентами, затем поднимается сервер и запускается тест-раннер
после оформления PR в pipepline запускается отдельный job, который собирает сборку с компонентами, поднимает сервер и запускает тест-раннер.

2021-06-15 14:39 UTC, Irinaristova commented on README.md
> +1. тест-раннер ищет файлы конфигурации в директории `src` и валидирует их
тест-раннер проходит по директории `src` и собирает файлы конфигурации.

2021-06-15 14:39 UTC, Irinaristova commented on README.md
> +1. если все найденные конфигурации валидны, запускается `playwright` с заранее заданными настройками. `playwright` используется тест-раннером для создания промежуточные скриншотов
описать порядок действий, если файлы не валидны.

2021-06-15 14:39 UTC, Irinaristova commented on README.md
> +1. если все найденные конфигурации валидны, запускается `playwright` с заранее заданными настройками. `playwright` используется тест-раннером для создания промежуточные скриншотов
если все найденные конфигурации валидны, запускается `playwright` с заранее заданными настройками. `playwright` используется тест-раннером для создания промежуточные скриншотов.

2021-06-15 14:39 UTC, Irinaristova commented on README.md
> +1. тест-раннер переходит на специальную страница теста с `url` в формате `/package/${packageName}/${componentName}-state-map`, находит корневой элемент `.state-map` (может поменяться), находит группы
насколько я поняла, тест-раннер формирует структуру (древовидную), мб про это тоже стоит кратко указать, потому что не понятно откуда взялся корневой элемент. И мб стоит немного описать, как формируются группы ?

2021-06-15 14:39 UTC, Irinaristova commented on README.md
> +1. после создания всех скриншотов текущего компонента запускается `express` сервер, для каждой группы рендерит через шаблон `pug` отдельную страница со скриншотами. Если есть переменная окружения PER
после создания всех скриншотов текущего компонента запускается `express` сервер, который  шаблон `pug` рендерит для каждой группы  отдельную страница со скриншотами.

2021-06-15 14:39 UTC, Irinaristova commented on README.md
> +1. после создания всех скриншотов текущего компонента запускается `express` сервер, для каждой группы рендерит через шаблон `pug` отдельную страница со скриншотами. Если есть переменная окружения PER
Если есть переменная окружения PERCY, то с помощью SDK `percy` создается  снапшот страницы для этой группы и отправляется на сервер.
В отсутствия переменной окружения  PERCY в директории `visual-testing/screensgots/${componentName}` создается тестовый скриншот с названием в формате `${group}-state-map`. После этого `express` сервер завершает работу.

2021-06-15 14:39 UTC, Irinaristova commented on README.md
> +1. после создания последнего снапшота все это отправляется на сервер `percy` и обрабатывается
после создания последнего снапшота сформируется percy объект, который включает все снапшоты, отправляется на сервер

2021-06-15 14:39 UTC, Irinaristova commented on README.md
> +1. после окончания обработки дизайнер получает уведомление, сравнивает диффы, если все хорошо, то делает approve
После обработки сервер формирует дифф, о чем уведомляются ревьюреры, указанные в pr.

2021-06-15 14:41 UTC, Irinaristova commented on README.md
> +
можно указать, что все примеру указываются для проекта woly

2021-06-16 08:22 UTC, sergeysova commented on README.md
> +Снапшот тестирование помогает отследить за нежелательными визуальными изменениями компонентов после изменения кодовой базы. Такой тест отображает ранее подготовленные страницы с кусочками пользовател
Может на английском эту доку?

2021-06-16 08:37 UTC, purplecandle commented on README.md
> +Снапшот тестирование помогает отследить за нежелательными визуальными изменениями компонентов после изменения кодовой базы. Такой тест отображает ранее подготовленные страницы с кусочками пользовател
Я думаю что смогу написать. @rchubarkin  @Irinaristova  @tatinacher  что думаете?

2021-06-16 09:26 UTC, Irinaristova commented on README.md
> +Снапшот тестирование помогает отследить за нежелательными визуальными изменениями компонентов после изменения кодовой базы. Такой тест отображает ранее подготовленные страницы с кусочками пользовател
мне так даже лучше читать будет

2021-06-16 13:23 UTC, tatinacher commented on README.md
> +Снапшот тестирование помогает отследить за нежелательными визуальными изменениями компонентов после изменения кодовой базы. Такой тест отображает ранее подготовленные страницы с кусочками пользовател
+

2021-06-16 13:33 UTC, tatinacher requested changes

2021-06-16 13:33 UTC, tatinacher commented on src/lib/state-map.tsx
> +}: {
Может типы аргументов функции вынести выше?

2021-06-16 13:33 UTC, tatinacher commented on src/lib/state-map.tsx
> +}: {
Можно также отсортировать по алфавиту

2021-06-18 17:26 UTC, Irinaristova commented on .gitignore
> -cypress/videos
а зачем это добавлять?

2021-06-18 17:26 UTC, Irinaristova commented on src/ui/atoms/button/__snapshot-testing__/index.tsx
> +        variant: ['primary', 'secondary', 'tertiary'],
варианты разве не будут тоже константами как и размеры?

2021-06-18 17:26 UTC, Irinaristova commented on visual-testing/index.js
> +// const { validateConfig } = require('./config-validator');
почему строка закоментирована?

2021-06-18 17:26 UTC, Irinaristova commented on visual-testing/index.js
> +const playwright = require('playwright');
а почему решил делать такие импорты?

2021-06-18 17:26 UTC, Irinaristova commented on visual-testing/index.js
> +    // optional
мб более развернутый комментарий оставить?

2021-06-18 17:26 UTC, Irinaristova commented on visual-testing/index.js
> +        // debug("validating component's config");
почему строки закоментированы?

2021-06-18 17:58 UTC, Irinaristova commented on src/ui/atoms/button/__snapshot-testing__/index.tsx
> +        size: ['N', 'XS', 'S', 'M', 'L', 'XL', 'H'] as const,
мб этот конфиг, если он повторяется вынести выше и сюда импортить? заметила, что ты во многих компонентах его копипастишь

2021-06-21 13:13 UTC, purplecandle commented on visual-testing/index.js
> +        // debug("validating component's config");
валидация была пока конфиги было простыми и в json формате. для тестирования сложных компонентов пришлось конфиг преобразовать в полноценный js файл и валидация уже стала сложной в рамках этой задачи, поэтому решил перенести его в отдельную таску

2021-06-21 13:24 UTC, purplecandle commented on visual-testing/index.js
> +// const { validateConfig } = require('./config-validator');
валидация была пока конфиги было простыми и в json формате. для тестирования сложных компонентов пришлось конфиг преобразовать в полноценный js файл и валидация уже стала сложной в рамках этой задачи, поэтому решил перенести его в отдельную таску

2021-06-21 13:26 UTC, purplecandle commented on .gitignore
> -cypress/videos
не понял вопрос

2021-07-08 09:23 UTC, risenforces approved these changes

2021-07-08 10:24 UTC, risenforces approved these changes

2021-07-08 12:51 UTC, sergeysova approved these changes

2021-07-08 14:53 UTC, risenforces approved these changes

2021-07-19 08:53 UTC, Irinaristova approved these changes

2021-07-19 09:51 UTC, rchubarkin submitted a review, later dismissed

2021-07-19 10:26 UTC, Irinaristova approved these changes

2021-07-19 10:28 UTC, rchubarkin approved these changes

2021-07-19 10:37 UTC, merged