feat: implement avatar component
woly-ui/woly pull request #143
Opened 2021-06-17 22:04 UTC by rchubarkin

2021-06-18 16:28 UTC, sergeysova requested changes

2021-06-18 16:28 UTC, sergeysova commented on src/ui/atoms/avatar/index.tsx
> +const imgStyles = css`
Для чего так?

2021-06-18 16:28 UTC, sergeysova commented on src/ui/atoms/avatar/index.tsx
> +  &[data-size='small'] {
Размер расчитывается через формулы, погляди например на кнопку и Block.L

2021-06-18 16:45 UTC, Irinaristova commented on src/ui/atoms/avatar/index.tsx
> +  width: var(--local-size);
можно задать 100%, чтобы аватар занимал весь объем контейнера и выбирать контейнер

2021-06-18 16:45 UTC, Irinaristova commented on src/ui/atoms/avatar/index.tsx
> +  --local-shape-color: var(--woly-shape-text-disabled);
разве он имеет цвет? серенькая сама иконка, а контейнер на макете вроде как transparent

2021-06-18 16:45 UTC, Irinaristova commented on src/ui/atoms/avatar/usage.mdx
> +| `size`     | `'default'` or `'small'` | `'default'` | avatar size                              |
отсортировать по алфавиту желательно

2021-06-18 16:45 UTC, Irinaristova commented on src/ui/atoms/avatar/usage.mdx
> +
мб сделаем пример, когда аватар вложенный компонент?

2021-06-18 16:45 UTC, Irinaristova commented on src/ui/atoms/avatar/index.tsx
> +const AvatarImage = styled.img`
мб сразу стили передавать, зачем создавать отдельный стайлед для этого?

2021-06-18 19:34 UTC, purplecandle requested changes

2021-06-18 19:34 UTC, purplecandle commented on src/ui/atoms/avatar/use-image-load.ts
> +    image.addEventListener('load', () => {
отписок не будет в unmount?

2021-06-18 19:34 UTC, purplecandle commented on src/ui/atoms/avatar/usage.mdx
> +| `variant`  | `string`                 | `'default'` | affetcs only avatar fallback color       |
мне кажется можно не указывать что это только для fallback. вдруг в примеру потом border появится, мы же не будем потом снова менять description

2021-06-22 08:12 UTC, sergeysova approved these changes

2021-06-22 08:12 UTC, sergeysova commented
@rchubarkin порешаешь конфликты?

2021-06-22 09:04 UTC, rchubarkin commented
> @rchubarkin порешаешь конфликты?

@sergeysova поправил конфликты

2021-06-23 07:43 UTC, Irinaristova commented on src/ui/atoms/avatar/index.tsx
> +const AvatarContainer = styled.div`
Если контейнер не экспортируется наружу, зачем создавать для него отдельный стайлед? Мб сразу стили прописать внутри аватара?

2021-06-23 08:15 UTC, rchubarkin commented on src/ui/atoms/avatar/index.tsx
> +const AvatarContainer = styled.div`
имеешь ввиду через css и className?

2021-06-23 08:39 UTC, rchubarkin commented on src/ui/atoms/avatar/index.tsx
> +const AvatarContainer = styled.div`
@sergeysova @purplecandle @tatinacher это проблема?

2021-06-23 10:06 UTC, sergeysova commented
@rchubarkin пофиксишь конфликты?

2021-06-23 10:12 UTC, purplecandle commented on src/ui/atoms/avatar/index.tsx
> +const AvatarContainer = styled.div`
думаю что возможно лишнее

2021-06-23 15:15 UTC, Irinaristova approved these changes

2021-06-23 16:13 UTC, sergeysova approved these changes

2021-06-23 16:13 UTC, merged