[FRNT-396] Rewrite data selectors
woly-ui/woly pull request #150
Opened 2021-06-24 09:40 UTC by tatinacher

- Rewrite data selectors
- Fix grammar bug
- Write code style guide for data-attribute

[FRNT-396]

2021-06-24 10:14 UTC, Irinaristova commented on src/woly/molecules/checkbox/index.tsx
> +          <span data-unchecked>
почему тут решила переименовать? Тут дата селектор управляет отрисовкой картинки, т.е. выполняет одну и ту же функцию, но для более высокой специфичности добавлены наименования

2021-06-24 10:14 UTC, Irinaristova commented on src/woly/molecules/field/index.tsx
> +    <div>{children}</div>
тут дата атрибут был добавлен чтобы  было понятно, что лежит внутри div, если в таком варианте оставить, то будет прочитан только текст внутри и все, для аксесабилити этот див будет бесполезен

2021-06-24 10:14 UTC, Irinaristova commented on src/woly/molecules/toast/index.tsx
> +    {icon && <span data-icon>{icon}</span>}
тут имя было добавлено для того, чтобы повысить специфичность, иначе иконка окрашивается не в тот цвет

2021-06-24 10:14 UTC, Irinaristova commented on src/woly/elements/input-container/index.tsx
> +    {rightIcon && <span data-icon>{rightIcon}</span>}
тут названия для дата атрибутов нужны по той же причине, что и в тосте: если rightIcon положить кнопку-иконку, иконка слева будет неправильного цвета

2021-06-24 10:23 UTC, sergeysova requested changes

2021-06-24 10:23 UTC, sergeysova commented on src/styleguide/html/data-attribute/data-attribute.mdx
> +```html
```suggestion
```

2021-06-24 10:23 UTC, sergeysova commented on src/woly/atoms/button/index.tsx
> +export type Buttonpriorities =
```suggestion
export type ButtonPriorities =
```

2021-06-24 10:23 UTC, sergeysova commented on src/woly/molecules/checkbox/index.tsx
> +          <span data-unchecked>
Наверное и data-icon не стоит удалять. Там же в боксе по нему компенсации применяются.
Они же тут нужны?

2021-06-24 10:23 UTC, sergeysova commented on src/woly/molecules/field/index.tsx
> +    <div>{children}</div>
```suggestion
    <div data-content>{children}</div>
```

2021-06-26 21:09 UTC, purplecandle commented on src/woly/atoms/button/usage.mdx
> +### priorities
```suggestion
### Priorities
```
И так вроде везде

2021-07-01 08:08 UTC, tatinacher commented on src/woly/molecules/toast/index.tsx
> +    {icon && <span data-icon>{icon}</span>}
Почему в тост добавляем значение для data-icon, а в кнопку/инпут нет, хотя и там есть иконки? Иконка окрашивается в нужный цвет, если по дата-атрибуту прописать стили.
Соглашусь, что можно добавить для специфичности, но тогда нужно добавлять во все компоненты, а не выборочно.

2021-07-01 14:51 UTC, Irinaristova commented on src/woly/molecules/checkbox/index.tsx
> +        <span data-icon>
тут лучше дать тоже название дата атрибуту, потому что, если чекбокс в отрисовке транспарент будет в айтеме селекта, а там будет еще и иконка, то цвет иконки чекбокса будет неправильный

2021-07-05 07:39 UTC, Irinaristova approved these changes

2021-07-05 12:29 UTC, rchubarkin submitted a review, later dismissed

2021-07-05 16:04 UTC, Irinaristova approved these changes

2021-07-06 08:27 UTC, Irinaristova approved these changes

2021-07-06 08:30 UTC, rchubarkin approved these changes

2021-07-06 10:36 UTC, sergeysova approved these changes

2021-07-06 10:36 UTC, merged