[FRNT-76 FRNT-60] Implement Navigation
woly-ui/woly pull request #152
Opened 2021-06-24 12:24 UTC by tatinacher

Implement Navigation component

2021-06-24 17:40 UTC, Irinaristova commented on src/lib/playground.tsx
> +    if (effect) {
можно короче effect && setValue(effect())

2021-06-24 17:40 UTC, Irinaristova commented on src/woly/molecules/navigation/index.tsx
> +          data-disabled={disabled}
разве ссылка в меню может быть задизейблена?

2021-06-24 17:40 UTC, Irinaristova commented on src/woly/molecules/navigation/index.tsx
> +    <ul className={className} data-priority={priority}>
Мб лучше было бы сделать контейнер компонент и компонент li и в него мапить ?

2021-06-24 17:40 UTC, Irinaristova commented on src/woly/molecules/navigation/usage.mdx
> +| `variant` | `string` | `'secondary'` | Variant prop to style ListContainer component |
priority и не все пропсы указаны

2021-06-24 17:40 UTC, Irinaristova commented on src/woly/molecules/navigation/index.tsx
> +    border: 1px solid var(--woly-shape-default);
почему кастомное значение бордера?

2021-06-24 17:40 UTC, Irinaristova commented on src/woly/molecules/navigation/index.tsx
> +      line-height: 24px;
тут бы формулу

2021-06-24 17:40 UTC, Irinaristova commented on src/woly/molecules/navigation/index.tsx
> +    ${box}
бокс вроде выставляет паддинги, зачем ниже их переопределять?

2021-06-24 17:40 UTC, Irinaristova commented on src/woly/molecules/navigation/index.tsx
> +  padding: 0 42px;
зачем тут паддинг прописывать? кастомные значения лучше вынести в переменную

2021-06-24 17:40 UTC, Irinaristova commented on src/woly/molecules/navigation/usage.mdx
> +import {Surface} from '../../atoms'
можно про import {Surface} from 'ui';

2021-06-28 12:34 UTC, purplecandle requested changes

2021-06-28 12:34 UTC, purplecandle commented on src/woly/molecules/navigation/index.tsx
> +          <div data-underline />
![image](https://user-images.githubusercontent.com/33234903/123635453-5f0c5c80-d824-11eb-8feb-e66a65b78c98.png)
Стоит наверное "прижать" эту линию вниз либо уже задать его через стили, а не отдельным элементом. Конечно, маловероятно, что будет такой длинный текст

2021-06-28 12:34 UTC, purplecandle commented on src/woly/molecules/navigation/usage.mdx
> +    active: false
Можно, наверное, не указывать явно что ссылка неактивная

2021-06-28 12:34 UTC, purplecandle commented on src/woly/molecules/navigation/usage.mdx
> +Another example of Menu component.
Этот пример не работает через клавиатуру

2021-06-30 11:16 UTC, tatinacher commented on src/woly/molecules/navigation/index.tsx
> +          data-disabled={disabled}
Саша говорит, что есть состояние disabled. Можем обсудить этот вопрос

2021-06-30 12:19 UTC, tatinacher commented on src/lib/playground.tsx
> +    if (effect) {
eslint на такое ругается)

2021-07-14 16:55 UTC, closed without merging

2021-07-14 16:56 UTC, Irinaristova commented
via [FRNT-543] https://liberty-base.atlassian.net/browse/FRNT-543?atlOrigin=eyJpIjoiN2FmOTJhNDllMGFiNDQ4YzllMDEzNmZmZTA3NTgxYWQiLCJwIjoiaiJ9