feat: add system-ui as a fallback font, add a font-weight vars
woly-ui/woly pull request #153
Opened 2021-06-24 14:13 UTC by purplecandle

Please, feel free to suggest another font-stacks

2021-06-24 17:25 UTC, Irinaristova commented on src/lib/global.ts
> +const fontFaces = css`
может лучше вынести в отдельный файл?

2021-06-24 17:25 UTC, Irinaristova commented on src/lib/global.ts
> +    /* Android */
это наверно лишнее?

2021-06-24 17:25 UTC, Irinaristova commented on src/lib/global.ts
> +  --system-ui:
а почему претир заигнорен?

2021-06-28 08:22 UTC, purplecandle commented on src/lib/global.ts
> +    /* Android */
а почему лишнее? наши компоненты не будут доступны в мобильной веб версии? или еще рано?

2021-06-28 08:23 UTC, purplecandle commented on src/lib/global.ts
> +  --system-ui:
потому что без игнора все будет в одну строку, хотелось бы чтобы комментарии и код чередовались строчно

2021-07-05 08:16 UTC, sergeysova requested changes

2021-07-05 08:16 UTC, sergeysova commented on src/lib/global.ts
> +    font-family: 'Helvetica Neue', var(--system-ui);
```suggestion
    font-family: 'Helvetica Neue', var(--font-system-ui);
```

2021-07-05 08:16 UTC, sergeysova commented on src/lib/global.ts
> +  --font-medium: 500;
```suggestion
  --font-weight-light: 300;
  --font-weight-regular: 400;
  --font-weight-medium: 500;
```

2021-07-05 08:16 UTC, sergeysova commented on src/lib/global.ts
> +  --font-medium: 500;
Но я не оч понимаю зачем оно надо?

Системные слова ровно эти значения и задают:

```css
font-weight: light; /* 300 */
```

2021-07-05 11:07 UTC, rchubarkin approved these changes

2021-07-05 14:59 UTC, Irinaristova approved these changes

2021-07-05 15:20 UTC, Irinaristova approved these changes

2021-07-05 15:24 UTC, Irinaristova submitted a review, later dismissed

2021-07-06 08:21 UTC, Irinaristova approved these changes

2021-07-06 08:22 UTC, rchubarkin approved these changes

2021-07-06 08:24 UTC, merged