[FRNT-560] add weight to button-icon
woly-ui/woly pull request #164
Opened 2021-06-29 10:13 UTC by Irinaristova

2021-07-05 11:58 UTC, purplecandle requested changes

2021-07-05 11:58 UTC, purplecandle commented on src/woly/atoms/button-icon/usage.mdx
> +| `weight`   | `string`                                     | `3`           | Set button-icon`s weight (ex.: fill, outline, transparent) |
```suggestion
| `weight`   | `string`                                     | `outline`           | Set button-icon`s weight (ex.: fill, outline, transparent) |
```

2021-07-05 11:58 UTC, purplecandle commented on src/woly/atoms/button-icon/index.tsx
> +  weight = '3',
```suggestion
  weight = 'outline',
```
Везде заменить

2021-07-05 13:29 UTC, purplecandle submitted a review, later dismissed

2021-07-05 13:30 UTC, rchubarkin approved these changes

2021-07-05 20:26 UTC, rchubarkin approved these changes

2021-07-06 08:46 UTC, purplecandle approved these changes

2021-07-06 08:46 UTC, merged