[FRNT-579] fix modal styles
woly-ui/woly pull request #172
Opened 2021-07-12 12:28 UTC by purplecandle

AS IS:

- heading has the same size in modals of different widths 
- modal doesn't have min/max width constraints 
- paddings between title and content are not calculated correctly 
- wrong padding of the modal content 
- the closing icon of the modal has no states

TO BE:

- reduce the size of the heading (consult with the designer)
- set min/max width
- paddings for the modal component are calculated by formulas (consult with the designer)
- the padding between title and content is calculated by the formulae
- the closing icon has states
- the closing icon is aligned with the title (consult with the designer)
- the icon is colored depending on the priority (consult with the designer)

2021-07-12 12:41 UTC, rchubarkin requested changes

2021-07-12 12:41 UTC, rchubarkin commented on src/woly/molecules/modal/index.tsx
> +            <block.XS data-button="modal-close">
блок только для usage

2021-07-12 12:41 UTC, rchubarkin commented on src/woly/molecules/modal/index.tsx
> +    padding-right: ${(props) => (props.onClose ? ' var(--local-gap)' : '0')};
вроде существует соглашение динамику не использовать? @sergeysova

2021-07-12 12:51 UTC, purplecandle commented on src/woly/molecules/modal/index.tsx
> +    padding-right: ${(props) => (props.onClose ? ' var(--local-gap)' : '0')};
сделаю через селекты

2021-07-12 13:21 UTC, Irinaristova commented on src/woly/molecules/modal/index.tsx
> +  padding: var(--local-vertical) var(--local-horizontal);
это бокс, не надо руками прописывать формулы, просто бокс добавь

2021-07-12 13:21 UTC, Irinaristova commented on src/woly/molecules/modal/index.tsx
> +  --local-vertical: calc(var(--woly-const-m) * (var(--woly-component-level) + 1));
откуда взялся 1? что за величина такая?

2021-07-12 13:21 UTC, Irinaristova commented on src/woly/molecules/modal/index.tsx
> +  -webkit-overflow-scrolling: touch;
в проекте есть плагин, который сам префиксы добавляет

2021-07-12 13:21 UTC, Irinaristova commented on src/woly/molecules/modal/index.tsx
> +    max-width: calc(36px * var(--woly-component-level) * var(--woly-main-level));
все значения вроде 36px лучше выносить в локальные переменные, если пока не готова формула, так легче будет их потом заменить

2021-07-12 13:21 UTC, Irinaristova commented on src/woly/molecules/modal/index.tsx
> +    overflow-x: hidden;
почему решил убрать скролл? а если контент будет больше, чем высота модалки? пользователь его уже не увидит просто

2021-07-12 13:21 UTC, Irinaristova commented on src/woly/molecules/modal/index.tsx
> +      margin-left: var(--local-gap);
почему margin-left у кнопки, а не у  margin-right у заголовка?

2021-07-12 13:21 UTC, Irinaristova commented on src/woly/molecules/modal/index.tsx
> +    margin-left: auto;
а ниже ты его переопределяешь ?

2021-07-12 13:21 UTC, Irinaristova commented on src/woly/molecules/modal/index.tsx
> +    --woly-component-level: 1;
это временное решение - задать кнопке фиксированный размер?

2021-07-12 13:21 UTC, Irinaristova commented on src/woly/molecules/modal/index.tsx
> +              <ButtonIcon onClick={onClose} icon={<IconClose />} />
а почему другие пропсы отсутствуют?

2021-07-12 13:24 UTC, purplecandle commented on src/woly/molecules/modal/index.tsx
> +  z-index: 999;
Да, это не должно было попасть

2021-07-12 13:28 UTC, purplecandle commented on src/woly/molecules/modal/index.tsx
> +  -webkit-overflow-scrolling: touch;
Это для плавного скрола в iOS устройствах. Раз для этой платформы мы еще не делаем, то удалю

2021-07-12 13:29 UTC, purplecandle commented on src/woly/molecules/modal/index.tsx
> +    overflow-x: hidden;
Имеешь в виду что контент будет больше чем ширина модалки? Как, например, таблица. Да, не стоит наверное

2021-07-12 13:30 UTC, purplecandle commented on src/woly/molecules/modal/index.tsx
> +      margin-left: var(--local-gap);
Если нет кнопки закрытия, то этот отступ и не нужен

2021-07-12 13:31 UTC, purplecandle commented on src/woly/molecules/modal/index.tsx
> +    --woly-component-level: 1;
Да, это временное решение. Я пока не очень понимаю, как каком уровне его контролировать

2021-07-12 16:00 UTC, purplecandle commented on src/woly/molecules/modal/index.tsx
> +    margin-left: auto;
пока решили оставить фиксом

2021-07-12 16:01 UTC, purplecandle commented on src/woly/molecules/modal/index.tsx
> +              <ButtonIcon onClick={onClose} icon={<IconClose />} />
добавил пропсы `prioity` и `weight`

2021-07-12 16:02 UTC, purplecandle commented on src/woly/molecules/modal/index.tsx
> +  padding: var(--local-vertical) var(--local-horizontal);
добавил, но `--local-vertical` не подходит, переопределил

2021-07-12 16:02 UTC, purplecandle commented on src/woly/molecules/modal/index.tsx
> +  --local-gap: calc(3px * var(--woly-component-level) * var(--woly-main-level));
выпрошу у дизайнера новую формулу

2021-07-13 10:07 UTC, risenforces commented
А можешь вкратце пояснить зачем программный "скролл лок"? Насколько помню я решал любые скроллы и прочее в модалках на уровне css

2021-07-13 13:43 UTC, purplecandle commented
> А можешь вкратце пояснить зачем программный "скролл лок"? Насколько помню я решал любые скроллы и прочее в модалках на уровне css

Я тоже делаю это на уровне css, просто вынес в отдельный хук. Если есть время, напиши свой альтернативный вариант

2021-07-14 09:34 UTC, purplecandle commented
Зачем сделал хук, а не просто вешаю класс `body.is-model-open { overflow: hidden }`:
- в Windows браузерах scrollbar съедает пространство у viewport. Когда у body ставится `overflow: hidden`, то scrollbar пропадает, и модалка "прыгает". В хук можно передать параметр `reserveScrollBarGap`, если он `true`, то у body добавится padding-right, который равен ширине скролла, чтобы предовратить этот флик. 
- он запоминает предыдущие стили у body перед тем, как заблокировать скролл, и возвращает их после разблокирования, поскольку у пользователя могли быть свои параметры `overflow` у body

2021-07-14 11:08 UTC, Irinaristova approved these changes

2021-07-14 12:15 UTC, rchubarkin approved these changes

2021-07-14 12:15 UTC, rchubarkin commented on src/woly/molecules/modal/index.tsx
> +    if (visible && modalRef.current) {
```suggestion
    if (!modalRef.current) return
    
    if (visible) {
      // ...
    } else {
      // ...
    }
```

2021-07-14 12:15 UTC, rchubarkin commented on src/woly/molecules/modal/index.tsx
> +  /* TODO: rewrite formulas */
**question:** вроде разговор был даты лепить на туду или чот такое)

2021-07-14 12:15 UTC, rchubarkin commented on src/woly/molecules/modal/use-scroll-lock.ts
> +      const reserveScrollBarGap = options.reserveScrollBarGap === true;
**question**: зачем выносить это в отдельный конст? можно просто обратиться к полю из опшенс

2021-07-14 12:15 UTC, rchubarkin commented on src/woly/molecules/modal/use-scroll-lock.ts
> +export const useScrollLock = (options: ScrollLockOptions = { reserveScrollBarGap: false }) => {
**praise:** клево что ты об это задумался, UX и складывается из подобных мелочей

2021-07-14 12:36 UTC, Irinaristova submitted a review, later dismissed

2021-07-14 12:36 UTC, risenforces submitted a review, later dismissed

2021-07-14 12:37 UTC, risenforces commented
> Зачем сделал хук, а не просто вешаю класс `body.is-model-open { overflow: hidden }`:
> 
> * в Windows браузерах scrollbar съедает пространство у viewport. Когда у body ставится `overflow: hidden`, то scrollbar пропадает, и модалка "прыгает". В хук можно передать параметр `reserveScrollBarGap`, если он `true`, то у body добавится padding-right, который равен ширине скролла, чтобы предовратить этот флик.
> * он запоминает предыдущие стили у body перед тем, как заблокировать скролл, и возвращает их после разблокирования, поскольку у пользователя могли быть свои параметры `overflow` у body

Забавно, я всегда забивал на горизонтальные флики)

2021-07-14 12:46 UTC, Irinaristova approved these changes

2021-07-14 12:56 UTC, Irinaristova approved these changes

2021-07-14 12:58 UTC, risenforces approved these changes

2021-07-14 12:59 UTC, merged