[FRNT-592] feat: implement level decrement
woly-ui/woly pull request #179
Opened 2021-07-21 12:32 UTC by rchubarkin

Компонент для автоматического уменьшения уровня. Предполагается что будет использоваться **только** как составная часть более сложных компонентов из дизайн системы.

Компонент содержит два уровня вложенности, каждый из которых можно кастомизировать: менять исходные теги/компоненты через пропы `as` / `innerAs` (по умолчанию и там и там `div`), навешивать стили через пропы `className` / `innerClassName`. Все прочие компоненты дестрактятся в компонент верхнего уровня.

2021-07-21 12:48 UTC, risenforces requested changes

2021-07-21 12:48 UTC, risenforces commented on src/woly/atoms/box/index.ts
> +export const Box = styled(LevelDecrement)`
**question(blocking)**: стили же накинутся на `Container`, а не на `Inner`, поэтому бокс не получится, не?

**suggestion**: вместо `innerAs` и т.д. сделать наоборот для `wrapper`, ведь мы обычно хотим стилизовать ближайшего родителя, а не самый высокий элемент в иерархии компонента

2021-07-21 12:48 UTC, risenforces commented on src/woly/atoms/box/index.ts
> +export const BoxVertical = styled(LevelDecrement)`
**question(blocking)**: стили же накинутся на `Container`, а не на `Inner`, поэтому бокс не получится, не?

**suggestion**: вместо `innerAs` и т.д. сделать наоборот для `wrapper`, ведь мы обычно хотим стилизовать ближайшего родителя, а не самый высокий элемент в иерархии компонента

2021-07-21 12:48 UTC, risenforces commented on src/woly/elements/level-decrement/index.tsx
> +}
**suggestion**: может стоит использовать для такого слово `rest`, ведь `props` это как бы весь объект пропсов, но тут только остаточные свойства

```suggestion
function LevelDecrementBase({
  children,
  as = 'div',
  className = '',
  innerAs = 'div',
  innerClassName = '',
  ...rest
}: LevelDecrementProps) {
  const Container = as;
  const Inner = innerAs;

  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <Container {...rest} className={className}>
      <Inner data-decrement-inner={true} className={innerClassName}>
        {children}
      </Inner>
    </Container>
  );
}
```

2021-07-21 12:50 UTC, risenforces commented
А у нас вообще могут всякие внутренние штуки быть в `atoms`? Или решаем просто на уровне экспортов?

2021-07-21 14:00 UTC, risenforces commented on src/woly/elements/level-decrement/index.tsx
> +}
**suggestion**: мне кажется тут стоит использовать `React.HTMLAttributes`, чтобы не повторять всякие `className`, `style` и тд

2021-07-21 17:00 UTC, rchubarkin commented on src/woly/elements/level-decrement/index.tsx
> +}
я думаю может че-то посложнее уже делать через `wrapperAs`? не хочется делать здоровую портянку типо `wrapperProps`

2021-07-21 18:17 UTC, risenforces commented on src/woly/elements/level-decrement/index.tsx
> +}
Думаю не стоит париться насчет враппера, ведь пока что накидывать в него пропсы нигде не пригодилось даже близко

Можно сделать чтобы по дефолту все шло во внутренний див и все

2021-07-23 10:08 UTC, Irinaristova commented on src/lib/global.ts
> +import * as wolyGlobal from 'ui/global';
suggestion(blocking):  у тебя получается 2 файла названы одним и тем же именем, один находится в src/lib/global.ts, второй - src/woly/global.ts и стайледы названы одинаково, почему нельзя использовать разные названия? сейчас из-за этого ты вынужден переопределять название стайледа на 1 строчке. Лучше сделать разные названия, например, GlobalStylesConfig & BaseStylesConfig

2021-07-23 11:54 UTC, risenforces commented on src/woly/elements/input-container/index.tsx
> +      <span {...levelDowngrade.props({ diff: 2 })} data-icon="input">
**suggestion**: мейби тоже уточнить, как с враппером?

```suggestion
      <span {...levelDowngrade.innerProps({ diff: 2 })} data-icon="input">
```

2021-07-23 11:57 UTC, risenforces commented on src/lib/global.ts
> +import * as wolyGlobal from 'ui/global';
+ за `Base`

А наружу можно экспортировать как `WolyGlobalStyles` и `WolyBaseStyles`

2021-07-23 12:23 UTC, rchubarkin reviewed
11

2021-07-23 12:25 UTC, rchubarkin commented on src/woly/elements/input-container/index.tsx
> +      <span {...levelDowngrade.props({ diff: 2 })} data-icon="input">
как будто это downgrade itself и это уточнение не нужно, или считаешь нужно?

2021-07-23 12:32 UTC, rchubarkin commented on src/lib/global.ts
> +import * as wolyGlobal from 'ui/global';
@Irinaristova @risenforces поправил на `WolyGlobalStyles`

2021-07-26 12:37 UTC, purplecandle commented on src/lib/global.ts
> +export const Global = styled(WolyGlobalStyles)`
**question:** почему просто не заинжектишь его?
То есть
```ts
import { levelDowngradeCss } from 'lib/level-downgrade';

export const Global = styled`
  ${levelDowngradeCss}
```

2021-07-26 12:45 UTC, purplecandle commented on src/lib/level-downgrade.ts
> +};
**thought**: Как-то совсем не заходит идея со спредом вызова функции. Какие возможности он дает? В чем преимущество от простого написания data-атрибутов? 

То есть
```tsx
const Comp = ({  children }) => {
  return <div data-lvl-downgrade-setup={true}>
    <div data-lvl-downgrade-diff={2}>{children}</div>
</div>
}
```

2021-07-26 17:38 UTC, risenforces commented on src/lib/global.ts
> +export const Global = styled(WolyGlobalStyles)`
Кстати думаю стоит еще подумать над вопросом именования таких штук, как минимум `Global` и `WolyGlobalStyles` выглядят странно из-за коллизии слова Global, мб стоит как-то разграничить вроде `WolyMinimalStyles`/`WolyBaseStyles`/`WolyRequiredStyles` и уже оттуда `WolyDefaultStyles`

Если разграничивать, мне кажется уже нет смысла указывать слово `Global`, так как и так понятно вроде, да и названия сильно удлинятся

2021-07-26 18:01 UTC, Irinaristova commented on src/lib/global.ts
> +import * as wolyGlobal from 'ui/global';
Тут суть в том, что одни стили у тебя глобальные только для воли, другие стили базовые для проекта, в котором используются компоненты воли.  Поэтому  минимальный конфиг, который экспортиться наружу  для корректной работы  воли с другим проектом, не стоит называть WolyGlobalStyles, поскольку название не соответсвует назначению конфига + у воли есть свой глобальный конфиг в проекте.

2021-07-26 21:10 UTC, rchubarkin commented on src/lib/level-downgrade.ts
> +};
импортировать проще чем запоминать, я понимаю когда селектор на атрибут в том же файле навешивается, но это вещь на уровне проекта

2021-07-26 21:13 UTC, rchubarkin commented on src/lib/global.ts
> +import * as wolyGlobal from 'ui/global';
Не вижу почему слова после "поэтому" следуют из того что было до них. Можешь развернуть? Как стоит назвать по-твоему?

2021-07-26 21:14 UTC, rchubarkin commented on src/lib/global.ts
> +export const Global = styled(WolyGlobalStyles)`
@purplecandle этот Global используется сейчас только в usage, наружу не торчит. А без этих стилей уровни работать не будут и нужно чтобы они были в проекте

2021-07-26 21:16 UTC, rchubarkin commented on src/lib/global.ts
> +export const Global = styled(WolyGlobalStyles)`
и ответ на этот вопрос есть в описании)

2021-07-27 08:45 UTC, Irinaristova commented on src/lib/global.ts
> +import * as wolyGlobal from 'ui/global';
Мне кажется, Женя предложил хороший вариант для нейминга

2021-07-28 10:19 UTC, purplecandle commented on src/woly/elements/input-container/index.tsx
> +      <span {...levelDowngrade.props({ diff: 2 })} data-icon="input">
**thought:** Тоже кажется, что нужно подумать над неймингом. Что делает первый data-атрибут? Он просто ининит всю эту логику downgrade, по мне, wrapperProps тут немного не подходит, в голову приходят такие слова как `init` или `setup`. Второй data-атрибут задействует всю эту логику, я бы использовал слово `use`.  Дописывание `props` тоже кажется излишним, потому что и так понятно, что еще можно спредить кроме пропсов. В итоге выглядело бы так:
```tsx
<div {...levelDowngrade.init()}>
  <div {...levelDowngrade.use({ diff: 2 })}>
    Level = Level - 2
  </div>
</div>
```
Конечно, все на твое усмотрение

2021-07-30 11:08 UTC, purplecandle approved these changes

2021-08-02 14:20 UTC, Irinaristova approved these changes

2021-08-03 07:49 UTC, purplecandle approved these changes

2021-08-03 08:28 UTC, risenforces approved these changes

2021-08-03 11:31 UTC, Irinaristova approved these changes

2021-08-03 16:17 UTC, merged