[DS-39] feat: implement time picker
woly-ui/woly pull request #184
Opened 2021-08-02 15:58 UTC by rchubarkin

2021-08-03 09:51 UTC, risenforces reviewed
Думаю внутри можно обойтись без стейта для значения, посмотрю попозже

2021-08-03 10:24 UTC, risenforces commented
Кстати в названии ветки нет задачи

2021-08-03 10:27 UTC, risenforces commented on src/calendar/time-picker/usage.mdx
> +import {block, Playground, StateEvent} from 'lib/playground'
**nitpick(blocking)**:

```suggestion
import {block, Playground, StateEvent} from 'dev/playground'
```

2021-08-03 10:38 UTC, risenforces commented
Странная штука, ты знаешь откуда это идет? Похоже оно где-то в gatsby-теме

![CleanShot 2021-08-03 at 15 37 13@2x](https://user-images.githubusercontent.com/35740512/128002107-d0984b1c-ee99-42d0-b648-b1355522b772.png)

2021-08-05 12:06 UTC, Irinaristova commented on src/calendar/time-picker/index.tsx
> +function scrollToSelectedItem(selectEl: HTMLElement) {
suggestion: мб стоит вынести эти хендлеры отдельно от самого компонента?

2021-08-05 12:06 UTC, Irinaristova commented on src/calendar/time-picker/usage.mdx
> +| ---------- | --------------------------------------------- | --------- | ------------------------------------------------------------------------------------- |
suggestion: не все пропсы описаны

2021-08-06 15:27 UTC, rchubarkin commented on src/calendar/time-picker/usage.mdx
> +| ---------- | --------------------------------------------- | --------- | ------------------------------------------------------------------------------------- |
Там ссылка на пропсы обычного инпута, типо смотри туда)

2021-08-09 08:48 UTC, risenforces commented on src/calendar/time-picker/usage.mdx
> +      </StateEvent>
**suggestion**: можно теперь на новые примеры заменить эти хуки) Если удобно конечно

2021-08-10 10:07 UTC, rchubarkin commented on src/calendar/time-picker/index.tsx
> +function scrollToSelectedItem(selectEl: HTMLElement) {
а куда?

2021-08-10 14:55 UTC, purplecandle commented on src/calendar/time-picker/index.tsx
> +          onClick={() => onChange(optionValue)}
**suggestion:** Тут прилетает event, который можно использовать вот так
```ts
onClick={(e: React.SyntheticEvent<HTMLElement>) => {
  selectedOptionRef.current = e.currentTarget;
  onChange(optionValue);
}}
```
чтобы избавиться от императивного кода в scrollToSelectedItem
```ts
  const selectedOptionRef = useRef<HTMLElement | null>(null);

  function scrollToSelected() {
    if (!selectRef.current) return;
    if (!selectedOptionRef.current) return;
    selectRef.current.scrollTo({ top: selectedOptionRef.current.offsetTop, behavior: 'smooth' });
  }
```

2021-08-11 10:31 UTC, purplecandle commented on src/calendar/time-picker/index.tsx
> +  }
```suggestion
  [data-element='stub'] {
    height: calc(var(--local-height) - var(--woly-line-height));
  }
```

2021-08-11 10:31 UTC, purplecandle commented on src/calendar/time-picker/index.tsx
> +      <li data-stub={true} />
```suggestion
      <li data-element='stub' />
```

2021-08-11 11:43 UTC, purplecandle commented on src/calendar/time-picker/index.tsx
> +    hourStep,
**suggestion**: Нужно сделать дополнительные проверки (не отрицательные, дробные и т.д.)

2021-08-11 11:46 UTC, purplecandle commented on src/woly/atoms/list/index.tsx
>      <span>{text}</span>
**suggestion:** Внутри применяется box и добавляет паддинги для span, но он инлайновый. Может стоит сделать его блочным либо потом применить box с направлением

2021-08-11 11:47 UTC, purplecandle requested changes
Оставил комментария 👆🏻

2021-08-12 10:13 UTC, rchubarkin commented on src/calendar/time-picker/index.tsx
> +    hourStep,
Решил все-таки не делать, похоже на лишнюю защиту от дурака

2021-08-13 08:50 UTC, purplecandle approved these changes

2021-08-13 10:03 UTC, Irinaristova approved these changes

2021-08-13 10:46 UTC, merged