feat(ui): implement chip atom
woly-ui/woly pull request #4
Opened 2020-08-13 06:43 UTC by tatinacher

Implement Chip atom

2020-08-16 15:08 UTC, sergeysova commented on src/ui/themes/dark.ts
> +  --background-color: #f8f8fa;
В этом случае `background-color` не понятно для чего.

2020-08-17 10:07 UTC, sergeysova commented on src/ui/atoms/chip/index.tsx
> +  onClose?: (event: React.SyntheticEvent) => void;
```suggestion
  onIconClick?: (event: React.SyntheticEvent) => void;
```
Иконкой же может быть не только кнопка закрытия Chip

2020-08-17 10:09 UTC, sergeysova commented on src/ui/themes/light.ts
> +  --chip-background-color: #f8f8fa;
В теме не должно быть никаких цветов связанных с компонентом.
Давай пока удалим все добавления из темы. Вместо этого будем опираться только на дефолтные значения переменных.

```css
.example {
  background-color: var(--chip-background-color, #f8f8fa);
}
```

2020-08-17 13:16 UTC, tatinacher commented on src/ui/atoms/chip/index.tsx
> +  onClose?: (event: React.SyntheticEvent) => void;
Обсудили с @n1zee , в Chip идет только иконка закрытия.

2020-08-17 13:47 UTC, sergeysova commented on src/ui/atoms/chip/index.tsx
> +  onClose?: (event: React.SyntheticEvent) => void;
Тогда нет никакого практического смысла пробрасывать пропс иконка.

Но я знаю кейс, когда может быть chip с другой иконкой, например +, это подсказка по контактам или тегам, где по клику на чип можно его открыть, а по плюсу добавить.

Я думаю гибче будет сделать как-то так:

```ts
interface ChipProps {
  icon?: React.ReactNode;
  onIconClick?: React.MouseEvent<HTMLButtonElement>;
}
```

2020-08-19 10:21 UTC, sergeysova requested changes

2020-08-19 10:21 UTC, sergeysova commented on src/ui/atoms/chip/index.tsx
> +  onClick?: (event: React.SyntheticEvent) => void;
```suggestion
  onClick?: React.MouseEventHandler<HTMLButtonElement>;
```

2020-08-19 11:09 UTC, sergeysova approved these changes

2020-08-19 11:09 UTC, merged