FRNT-174 : add component text-area
woly-ui/woly pull request #53
Opened 2021-03-09 16:21 UTC by Irinaristova

2021-03-12 11:10 UTC, sergeysova requested changes

2021-03-12 11:10 UTC, sergeysova commented on yarn.lock
> +<<<<<<< Updated upstream
У тебя тут конфликты в ярн файл затесались, надо бы Удалить их и установить зависимости заново

2021-03-19 11:22 UTC, sergeysova requested changes

2021-03-19 11:22 UTC, sergeysova commented on src/lib/box-styles.tsx
> +    --woly-count-color: #c4c4c4;
Проблема этого имени в том, что оно четко объявляет место использования: только для использования внутри счетчиков. Но на самом деле, этот же цвет может быть использован для любых подсказок.

Я думаю его можно переименовать в `hint-color`

2021-03-19 11:22 UTC, sergeysova commented on src/ui/atoms/input/example.tsx
> +              label={<Label text="Error text" />}
```suggestion
              label="Error text"
```

Не стоит заставлять пользователя импортировать компонент и дополнительно заворачивать обычный текст в компонент. Заверни в компонент внутри, самостоятельно.

Пусть компонент позволяет пользоваться с удобством.

2021-03-19 11:22 UTC, sergeysova commented on src/ui/atoms/input/index.tsx
> +  <InputWrapper data-variant={variant}>
Не стоит создавать дополнительный стайлед-компонент внутри стайледа.
Внизу уже есть компонент Input.

Допиши в нем стили для input.
или же добавь дополнительный враппер и пометь его нужным `data-attr`

Например так:

```jsx
() => (
  <div className={className} data-block="container" data-variant={variant}>
    <input name={name} onChange={onChange} type={type} {...props} />
    {label && <Label text={label} />}
  </div>
)
```

2021-03-19 11:22 UTC, sergeysova commented on src/ui/atoms/input/index.tsx
> +  <InputWrapper data-variant={variant}>
`className` здесь проваливается из styled-компонента Input, а значит все стили можно писать относительно него.

2021-03-19 11:22 UTC, sergeysova commented on src/ui/atoms/input/index.tsx
> +}
кажется здесь стили съехали

2021-03-19 11:22 UTC, sergeysova commented on src/ui/atoms/text-area/index.tsx
> +        className={className}
className нужно вешать на корневой элемент компонента, чтобы не создавать вложенные стайледы.

Давай возьмем за правило, на один компонент woly, создаем один styled компонент.

2021-03-19 11:22 UTC, sergeysova commented on src/ui/atoms/text-area/index.tsx
> +      <Containrer>
Тогда и не понадобятся вложенные компоненты.
сможешь их просто помечать:

```suggestion
      <div data-block="container">
```

2021-03-19 11:22 UTC, sergeysova commented on src/ui/atoms/text-area/index.tsx
> +  --woly-vertical: calc(
И не придется дублировать описание этих переменных

2021-03-19 11:22 UTC, sergeysova commented on src/ui/atoms/text-area/index.tsx
> +      {label && <span>{label}</span>}
Не стоит мучать пользователя необходимостью импортировать лейбл.

2021-03-21 13:49 UTC, sergeysova commented on src/ui/atoms/text-area/index.tsx
> +--woly-width: 100%;
Кажется, стили сломались?

2021-03-22 09:20 UTC, tatinacher requested changes

2021-03-22 09:20 UTC, tatinacher commented on src/ui/atoms/text-area/example.tsx
> +              ref={textareaRef}
@Irinaristova prop же textareaRef, а не ref?

2021-03-22 09:20 UTC, tatinacher commented on src/ui/atoms/text-area/index.tsx
> +  return (
@Irinaristova можешь убрать return?

2021-03-22 09:20 UTC, tatinacher commented on src/ui/atoms/text-area/index.tsx
> +  className?: string;
@Irinaristova отсортируешь по алфавиту?

2021-03-22 09:20 UTC, tatinacher commented on src/ui/atoms/text-area/index.tsx
> +    border-color: var(--woly-border-focus, #000000);
@Irinaristova можешь убрать outline на focus? и в примере не видно, как меняется border на focus

2021-03-22 09:20 UTC, tatinacher commented on src/ui/atoms/text-area/usage.mdx
> +| `name`     | `string`                                                      |             | Name attribute specifies a name of the text-area                             |
@Irinaristova Не хватает пропсов (maxLength и тп)

2021-03-22 10:29 UTC, Irinaristova commented on src/ui/atoms/text-area/index.tsx
> +    border-color: var(--woly-border-focus, #000000);
<img width="331" alt="Снимок экрана 2021-03-22 в 13 29 02" src="https://user-images.githubusercontent.com/38761239/111976397-a0e58280-8b12-11eb-9361-e9f028aa0471.png">

2021-03-22 10:29 UTC, Irinaristova commented on src/ui/atoms/text-area/index.tsx
> +    border-color: var(--woly-border-focus, #000000);
border  при фокусе

2021-03-24 11:14 UTC, tatinacher commented on src/ui/atoms/text-area/index.tsx
> +    border-color: var(--woly-border-focus, #000000);
На скрине outline. Есть пример в input, там бордер меняется на focus.
<img width="499" alt="Снимок экрана 2021-03-24 в 14 12 20" src="https://user-images.githubusercontent.com/28189463/112301641-34ea5200-8cab-11eb-8ec6-ebb964c4436f.png">

2021-03-24 11:18 UTC, tatinacher requested changes

2021-03-24 11:18 UTC, tatinacher commented on src/ui/atoms/text-area/index.tsx
> +    border-color: var(--woly-border-focus, #000000);
@Irinaristova нужно добавить `outline: none` для textarea и на focus, active менять цвет border, можешь посмотреть как у input сделално

2021-03-25 09:29 UTC, sergeysova approved these changes

2021-03-25 13:51 UTC, tatinacher approved these changes

2021-03-25 17:24 UTC, merged