feat: implement tooltip FRNT-175
woly-ui/woly pull request #55
Opened 2021-03-12 11:32 UTC by tatinacher

Task [FRNT-175](https://liberty-base.atlassian.net/browse/FRNT-175)

2021-03-12 11:38 UTC, sergeysova requested changes

2021-03-12 11:38 UTC, sergeysova commented on src/ui/atoms/tooltip/index.tsx
> +    filter: drop-shadow(3px 3px 9px rgba(57, 57, 57, 0.12));
Почему через фильтр, а не box-shadow?

2021-03-12 11:38 UTC, sergeysova commented on src/ui/atoms/tooltip/index.tsx
> +    width: ${({ width }) => (width ? `${width}px` : 'inherit')};
Давай попробуем не вставлять функции в стайл. Можно так же использовать дата-attr

2021-03-12 13:58 UTC, tatinacher commented on src/ui/atoms/tooltip/index.tsx
> +    width: ${({ width }) => (width ? `${width}px` : 'inherit')};
Тогда задать width значения 's', 'm', 'l'?

2021-03-12 21:29 UTC, sergeysova commented on src/ui/atoms/tooltip/index.tsx
> +    width: ${({ width }) => (width ? `${width}px` : 'inherit')};
Можно задавать любое значение атрибута. Но тут кажется по умолчанию должен быть размер по ширине контента, с ограничением максимальной ширины.

2021-03-19 11:06 UTC, sergeysova requested changes

2021-03-19 11:06 UTC, sergeysova commented on src/lib/tooltip.tsx
> +type PositionProps = 'bottom' | 'top' | 'left' | 'right';
Кажется, что здесь идет расчет позиции, а не tooltip. Потенциально эту библиотеку можно использовать для select.

Думаю, лучше переименовать в `lib/position-relative`

2021-03-19 11:06 UTC, sergeysova commented on src/lib/tooltip.tsx
> +export const getPosition = ({ position, id }: GetPositionProps) => {
Давай попробуем именовать функции и методы в таком формате:

https://gist.github.com/sergeysova/9f6dc24e21efe5f5bb4f9878216c2ce9

```suggestion
export const positionRelativeGet = ({ position, id }: GetPositionProps) => {
```

2021-03-22 13:58 UTC, Irinaristova commented on src/ui/atoms/tooltip/index.tsx
> +    max-width: 295px;
@sergeysova, @tatinacher  решили пока харкодить max-width ?

2021-03-22 13:58 UTC, Irinaristova commented on src/ui/atoms/tooltip/usage.mdx
> +| `children` | `React.ReactElement`                  |             | The tooltip will be visible near `children` on hover |
тут id вроде не хватает

2021-03-22 13:58 UTC, Irinaristova commented on src/ui/atoms/tooltip/index.tsx
> +    document.addEventListener('scroll', onScroll);
а тут разве не нужно потом сделать removeEventlistener ?

2021-03-22 15:22 UTC, Irinaristova commented on src/lib/tooltip.tsx
> +  if (window && document) {
ты тут получаешь элементы через querySelector, но это же можно сделать через React.Ref, ты точно будешь получать положение именно твоего tooltip относительно страницы  (потому что на странице могут быть и другие tooltip с такими id), плюс кода будет немного меньше, вот похожий пример https://codereview.stackexchange.com/questions/215217/stateless-tooltip-component-using-react-hooks-and-ref

2021-03-23 11:08 UTC, tatinacher commented on src/ui/atoms/tooltip/index.tsx
> +    max-width: 295px;
@Irinaristova договорились с дизайнером Сашей

2021-03-24 09:06 UTC, Irinaristova approved these changes

2021-03-25 12:37 UTC, sergeysova requested changes

2021-03-25 12:37 UTC, sergeysova commented on src/ui/atoms/tooltip/index.tsx
> +  }, [position, document]);
Нужно быть сюда добавить ref, ведь onScroll будет пересоздаваться на изменение ref.
А значит, если изменится ref, то onScroll будет пересоздан, а отписка на событие scroll не произойдет

2021-03-25 12:37 UTC, sergeysova commented on src/ui/atoms/tooltip/index.tsx
> +      data-id={id}
для чего здесь `data-id` ?

2021-03-30 15:13 UTC, sergeysova requested changes

2021-03-30 15:13 UTC, sergeysova commented on src/ui/atoms/tooltip/example.tsx
> +  <Global>
Реализуй примеры в стиле button в файле usage.mdx, пожалуйста.

2021-04-02 09:34 UTC, sergeysova commented on src/ui/atoms/tooltip/example.tsx
> +  <Global>
Пусть это будет исправлено в FRNT-395

2021-04-02 09:34 UTC, sergeysova approved these changes

2021-04-02 09:34 UTC, merged