[FRNT-191]  implement new chip version
woly-ui/woly pull request #56
Opened 2021-03-14 10:02 UTC by Irinaristova

2021-03-19 11:12 UTC, sergeysova requested changes

2021-03-19 11:12 UTC, sergeysova commented on src/ui/atoms/chip/example.tsx
> +          role="button"
Chip должен сам назначать роль и tabIndex внутри себя, в зависимости от наличия onClick.

Не стоит заставлять пользователей библиотеки делать это вручную.

2021-03-19 11:12 UTC, sergeysova commented on src/ui/atoms/chip/index.tsx
> +      </div>
Смотри, у нас может быть:
1. чип, по которому можно кликнуть `<Chip onClick={fn}>Text</Chip>`
2. просто чип, как лейбл `<Chip>Label</Chip>`
3. чип, по которому можно кликнуть и дополнительно иконка справа, которая является кнопкой экшена `<Chip onClick={fn} action={<CloseIcon />} onActionClick={fn}>Chip with close</Chip>`
4. просто чип с иконкой-кнопкой `<Chip action={<CloseIcon />} onActionClick={fn}>Label with close</Chip>`

Сейчас же я вижу только чип с кнопкой. Давай доделаем реализацию

2021-03-22 08:26 UTC, tatinacher commented on src/ui/atoms/chip/index.tsx
> +      </div>
@sergeysova может onActionClick={fn} передавать внутрь компонента action? `<Chip action={<CloseIcon onActionClick={fn} />}>Label with close</Chip>`

2021-03-22 08:33 UTC, tatinacher commented on src/ui/atoms/chip/index.tsx
>    children?: never;
@Irinaristova можешь отсортировать по алфавиту пропсы тут и ниже?

2021-03-22 08:41 UTC, tatinacher commented on src/ui/atoms/chip/index.tsx
> +          {icon}
@Irinaristova чип с иконкой выглядит как то так: 
<img width="442" alt="Снимок экрана 2021-03-22 в 11 39 37" src="https://user-images.githubusercontent.com/28189463/111962532-763ffd80-8b03-11eb-98d9-74c75cb57851.png">

2021-03-22 09:20 UTC, tatinacher requested changes

2021-03-22 09:31 UTC, tatinacher commented on src/ui/atoms/chip/index.tsx
> +  return(
@Irinaristova можешь убрать return?

2021-03-22 10:32 UTC, Irinaristova commented on src/ui/atoms/chip/index.tsx
> +  return(
я обновила пр, теперь там return нужен

2021-03-22 14:32 UTC, Irinaristova commented on src/ui/atoms/chip/index.tsx
> +      </div>
<img width="373" alt="Снимок экрана 2021-03-22 в 17 31 22" src="https://user-images.githubusercontent.com/38761239/112006072-6db3eb00-8b34-11eb-9d7a-505c2059e4a6.png">
так а там по-другому и не получится, я вот так сделала сейчас

2021-03-25 13:40 UTC, tatinacher commented on src/ui/atoms/chip/index.tsx
> +      </div>
@Irinaristova я имела ввиду, что можно передавать в качестве пропса action не только иконку, а сразу компонент `<ButtonIcon icon={icon} onClick={onActionClick} ... /> `, и внутри компонента Chip вывести просто {action}, отпозиционировав его справа. Это просто как вариант реализации.

2021-03-25 13:43 UTC, tatinacher commented on src/ui/atoms/chip/index.tsx
> +          {icon}
@Irinaristova у меня все так же показываются иконки(

2021-03-25 13:47 UTC, tatinacher requested changes

2021-03-25 13:47 UTC, tatinacher commented on src/ui/atoms/chip/index.tsx
> +  [role]:hover {
нужен ли hover на некликабельный Chip?

2021-03-25 13:47 UTC, tatinacher commented on src/ui/atoms/chip/index.tsx
> +        <button
Если тут button то нужно стили поправить, убрать у кнопки border и background, чтобы ток иконка была как в макетах

2021-03-26 08:05 UTC, Irinaristova commented on src/ui/atoms/chip/index.tsx
> +        <button
Саша переделает chip в макете

2021-03-30 12:17 UTC, tatinacher requested changes

2021-03-30 12:17 UTC, tatinacher commented on src/ui/atoms/chip/index.tsx
> +    padding-right: ${(props) => (props.action && "var(--woly-right-offset)")};
@Irinaristova я в кнопке реализовала изменение padding без props, у меня в зависимости от наличия иконки просто стилями меняется паддинг. Мб тут тоже так сделать?

2021-03-30 15:00 UTC, sergeysova requested changes

2021-03-30 15:00 UTC, sergeysova commented on src/ui/atoms/chip/example.tsx
> +      <block.S>
Перенеси все примеры в usage.mdx, пожалуйста.
По примеру компонента button

2021-03-30 15:00 UTC, sergeysova commented on src/ui/atoms/chip/index.tsx
> +  const divTabIndex = onClick ? 1 : 0 ;
```suggestion
  const chipRole = onClick ? 'button' : 'div';
  const chipTabIndex = onClick ? 1 : 0 ;
```

Лучше давать осмысленные имена. Гляди, чтобы понять, что значит div в названии этих переменных нужно посмотреть как они используются ниже в коде, а затем понять, почему там div.

Мне кажется, если добавить сюда сразу четко обозначающее название, будет круче и понятнее

2021-03-30 15:00 UTC, sergeysova commented on src/ui/atoms/chip/index.tsx
> +  return(
```suggestion
  return (
```

похоже, что тут потерялось форматирование

2021-03-30 15:00 UTC, sergeysova commented on src/ui/atoms/chip/index.tsx
> +        <button
В итоге, договорились, что здесь есть иконка, у которой срабатывает подсветка квадратной плашки. Но Саша будет искать более качественное решение, чтобы не срабатывало два hover.

(замержим как есть, пока что, другие доработки отдельным ПР)

2021-03-30 15:00 UTC, sergeysova commented on src/ui/atoms/chip/index.tsx
> +  [role]:hover {
По идее, не нужен.
Если нельзя кликнуть на Chip, то он не должен никак реагировать при наведении

2021-03-30 15:00 UTC, sergeysova commented on src/ui/atoms/chip/index.tsx
> +    cursor: pointer;
Напишу сюда и вынесу потом в правила:
- Если элемент можно кликнуть и пользователь сможет четко определить, что его состояние изменилось (при наведении), то курсор менять не нужно
- Если же при наведении лишь незначительно меняется цвет или так же незначительно меняется размер или позиция, то нужно менять cursor на pointer.

В данном случае, при наведении на Chip будет меняться его состояние — изменится цвет, курсор менять нет необходимости, на мой взгляд.
Если считаешь иначе, опиши почему, может быть я ошибаюсь

2021-03-30 15:00 UTC, sergeysova commented on src/ui/atoms/chip/index.tsx
> +  &[data-disabled='true'] [data-icon]{
Похоже тут отвалилось форматирование stylelint. Похоже, что у тебя в IDE он не включен ли не работает.

2021-03-30 15:00 UTC, sergeysova commented on src/ui/atoms/chip/index.tsx
> +      var(--woly-background-disabled, #000000)
Кажется, это не очень. Неужели есть практическая ситуация когда border-disabled отсутствует, но при этом есть background-disabled.

По идее, все переменные из списка должны быть заранее определены, в глобальных стилях в секции data-variant

2021-04-07 09:48 UTC, sergeysova approved these changes

2021-04-07 09:49 UTC, merged