FRNT-329  add checkbox component
woly-ui/woly pull request #57
Opened 2021-03-23 15:27 UTC by Irinaristova

2021-03-23 16:19 UTC, Irinaristova commented
реализовала 2 варианта стилизации checkbox на выбор

2021-03-24 10:51 UTC, tatinacher requested changes

2021-03-24 10:51 UTC, tatinacher commented on src/ui/molecules/checkbox/index.tsx
> +  color?: string;
@Irinaristova зачем передавать color как проп? мб лучше задать его как css variable?

2021-03-24 10:51 UTC, tatinacher commented on src/ui/molecules/checkbox/usage.mdx
> +| `icon`      | `React.ReactNode`                            |             | Set the icon component inside the checkbox          |
@Irinaristova а тут color нету

2021-03-24 10:51 UTC, tatinacher commented on src/ui/molecules/checkbox/index.tsx
> +  text,
@Irinaristova у toggle совсем убрали label, а тут заменили label на text. 
По сути текст-разъяснение нужен и для toggle и для checkbox, но в чекбокс можем передать текст, а в toggle нет, что думаешь?

2021-03-24 11:45 UTC, Irinaristova commented on src/ui/molecules/checkbox/index.tsx
> +  text,
Не совсем, это разные тексты,  checkbox может быть как 1, так и group, и у group label расположен сверху, то, что располагается справа/слева от checkbox это простой текст. У toggle текста нет совсем, у него может быть только label, поэтому его удалили, как и у всех остальных элементов. Label добавлять в контейнер-обертку, которая также будет принимать и компонент: input, toggle etc.

2021-03-24 11:58 UTC, tatinacher commented on src/ui/molecules/checkbox/index.tsx
> +  text,
окей 👌

2021-03-24 12:52 UTC, Irinaristova commented on src/ui/molecules/checkbox/index.tsx
> +  color?: string;
в принципе можно и через переменные это делать

2021-03-25 09:25 UTC, sergeysova requested changes

2021-03-25 09:25 UTC, sergeysova commented on src/ui/molecules/checkbox/example.tsx
> +          icon={<CheckIcon />}
Не стоит заставлять пользователей передавать icon.

2021-03-31 10:27 UTC, sergeysova approved these changes

2021-03-31 10:27 UTC, sergeysova commented on src/ui/molecules/checkbox/usage.mdx
> +  <CheckboxExample variant="base"/>
Можешь здесь тоже добавить примеры как в button usage?

2021-03-31 12:54 UTC, tatinacher requested changes

2021-03-31 12:54 UTC, tatinacher commented on src/ui/molecules/checkbox/index.tsx
> +import { CheckIcon } from 'icons';
@Irinaristova Вижу что ты импортируешь иконку только для состояния isChecked=true, а для состояния isChecked=false отрисовываешь? Выглядит не так, как в макете, может для состояния isChecked=false тоже импортировать иконку? 
<img width="423" alt="Снимок экрана 2021-03-31 в 15 49 40" src="https://user-images.githubusercontent.com/28189463/113146739-b6585c00-9238-11eb-9a39-7a1e52d011d7.png">

2021-03-31 12:54 UTC, tatinacher commented on src/ui/molecules/checkbox/index.tsx
>  }
@Irinaristova подскажи, в данной реализации решили, что свои иконки для чекбокса пользователь передать не может?

2021-03-31 12:54 UTC, tatinacher commented on src/ui/molecules/checkbox/index.tsx
> +    <div data-block="container" data-disabled={disabled}>
@Irinaristova По спецификации `div` внутрь `label` прокидывать нельзя

2021-03-31 14:35 UTC, Irinaristova commented on src/ui/molecules/checkbox/index.tsx
> +import { CheckIcon } from 'icons';
@tatinacher это одна и та же иконка, я в ней просто меняю заливку для fill и stroke

2021-03-31 14:35 UTC, Irinaristova commented on src/ui/molecules/checkbox/index.tsx
> +    <div data-block="container" data-disabled={disabled}>
по какой спецификации? где это можно прочитать?

2021-03-31 14:36 UTC, Irinaristova commented on src/ui/molecules/checkbox/index.tsx
>  }
иконка будет просто зашиты внутрь

2021-03-31 15:16 UTC, tatinacher commented on src/ui/molecules/checkbox/index.tsx
> +    <div data-block="container" data-disabled={disabled}>
https://stackoverflow.com/questions/18609554/is-div-inside-label-block-correct

2021-03-31 15:17 UTC, tatinacher commented on src/ui/molecules/checkbox/index.tsx
> +import { CheckIcon } from 'icons';
У тебя нормально отображается? У меня в хроме как на скине который выше скинула(

2021-03-31 15:26 UTC, Irinaristova commented on src/ui/molecules/checkbox/index.tsx
> +    <div data-block="container" data-disabled={disabled}>
так по спеке там и инпута быть не должно, label принимает в себя только текст, а у нас там инпут, который мы скрываем + иконки и по сути мы используем хак

2021-04-02 09:59 UTC, sergeysova requested changes

2021-04-02 09:59 UTC, sergeysova commented on src/lib/box-styles.tsx
> +    --woly-checkbox-color: #eb5656;
В теме не должно быть информации о компонентах.

2021-04-02 09:59 UTC, sergeysova commented on src/ui/molecules/checkbox/index.tsx
> +      <span data-block="checkmark-checked">{<CheckIcon />}</span>
думаю эти два компонента можно пометить слегка удобнее:
```suggestion
      <span data-checkmark="unchecked">{<UnCheckIcon />}</span>
      <span data-checkmark="checked">{<CheckIcon />}</span>
```

2021-04-02 09:59 UTC, sergeysova commented on src/ui/molecules/checkbox/index.tsx
> +    [data-block='checkmark-unchecked'] {
И здесь станет приятнее:
```suggestion
    [data-checkmark] {
```

2021-04-02 09:59 UTC, sergeysova commented on src/ui/molecules/checkbox/index.tsx
> +    }
```suggestion
    [data-checkmark='unchecked'] {
      display: block;
    }

    [data-checkmark='checked'] {
      display: none;
    }
```

2021-04-02 09:59 UTC, sergeysova commented on src/ui/molecules/checkbox/index.tsx
> +    }
Таким образом одним и тем же селектором, можно выбирать два элемента

2021-04-02 09:59 UTC, sergeysova commented on src/ui/molecules/checkbox/usage.mdx
> +  <CheckboxExample variant="base"/>
А вот импорт CheckboxExample лучше удалить, ведь тогда его исходный код не видно на странице документации

2021-04-06 18:44 UTC, sergeysova approved these changes

2021-04-06 18:44 UTC, sergeysova commented on src/ui/molecules/checkbox/index.tsx
> +      <span data-checkmark="unchecked">{<UnCheckIcon />}</span>
```suggestion
      <span data-checkmark="unchecked"><UnCheckIcon /></span>
```
Они же не нужны там

2021-04-06 18:45 UTC, sergeysova approved these changes

2021-04-07 09:43 UTC, sergeysova approved these changes

2021-04-07 09:46 UTC, merged