[FRNT-334] modify label component
woly-ui/woly pull request #58
Opened 2021-03-23 15:46 UTC by Irinaristova

2021-03-24 10:07 UTC, tatinacher requested changes

2021-03-24 10:07 UTC, tatinacher commented on src/ui/atoms/label/index.tsx
>    text: React.ReactNode;
@Irinaristova мб у text будет тип string? Мы же лейблу будем ток строку передавать или нет?

2021-03-24 10:07 UTC, tatinacher commented on src/ui/atoms/label/usage.mdx
@Irinaristova сверху на 10 строчке надо убрать `Label can be passed as a property to a Checkbox or a Toggle component.` тк не актуально

2021-03-24 10:25 UTC, Irinaristova commented on src/ui/atoms/label/index.tsx
>    text: React.ReactNode;
да, у текста поменяю тип. добавила children потому, что, например, error label часто содержит еще и icon или hint, а, если убрать children, мы сильно ограничиваем лейб

2021-03-24 11:03 UTC, tatinacher commented on src/ui/atoms/label/index.tsx
>    text: React.ReactNode;
Сейчас если передаешь children, то он вообще не показывается в Label. 
Мб или оставить у text тип React.ReactNode и убрать children, или убрать вообще text и передавать то, что показываешь в лейбле, в children .

2021-03-24 12:21 UTC, Irinaristova commented on src/ui/atoms/label/index.tsx
>    text: React.ReactNode;
переделала компонент label совсем, чтобы он был в одной стилистике по коду, мне кажется там более читабельно, убрала стилизацию через attr, потому что там динамические изменения не нужны по сути

2021-03-25 13:13 UTC, tatinacher approved these changes

2021-03-25 17:26 UTC, sergeysova requested changes

2021-03-25 17:26 UTC, sergeysova commented on src/ui/atoms/label/index.tsx
> +}) => <label data-variant={variant}>{children}</label>;
```suggestion
}) => <label className={className} data-variant={variant}>{children}</label>;
```
иначе стили не применятся.

а вообще такое лучше делать через [`.attrs`](https://styled-components.com/docs/faqs#when-to-use-attrs)

2021-03-29 15:53 UTC, sergeysova requested changes

2021-03-29 15:53 UTC, sergeysova commented on src/ui/atoms/label/index.tsx
> +export const Label = styled.div.attrs(map)`
Так там же раньше был `label`, а теперь `div`. Кажется, что правильным должен быть `label`

2021-03-29 15:53 UTC, sergeysova commented on src/ui/atoms/label/index.tsx
> +  children: properties.children,
Насколько я помню, `children` можно не прописывать, они автоматом пробросятся

2021-03-29 15:53 UTC, sergeysova commented on src/ui/atoms/label/usage.mdx
> +This increased hit area provides an advantage to anyone trying to activate the input, including those using a touch-screen device.
Докинь примеров использования завернутых в `Playground`, [по примеру Button](https://github.com/woly-ui/woly/blob/5d99dabd2f018e23a23380d14af2e23f356013a7/src/ui/atoms/button/usage.mdx)

2021-03-31 10:28 UTC, sergeysova approved these changes

2021-03-31 10:29 UTC, merged