[FRNT-336] remove label from components
woly-ui/woly pull request #59
Opened 2021-03-23 15:56 UTC by Irinaristova

2021-03-24 09:50 UTC, tatinacher requested changes

2021-03-24 09:50 UTC, tatinacher commented on src/ui/molecules/toggle/index.tsx
> -      {label && <span style={{ cursor: 'pointer' }}>{label}</span>}
@Irinaristova внизу можно убрать стили 
`  label > *:not(:first-child) {
    margin-left: var(--woly-gap);
  }`
тк у toggle остается отступ слева без label. Ну и добавить отступы в примере, чтобы компоненты не слипались

2021-03-24 10:19 UTC, Irinaristova commented on src/ui/molecules/toggle/index.tsx
> -      {label && <span style={{ cursor: 'pointer' }}>{label}</span>}
в рамках этой таски я убирала просто компонент label, стили у самого toggle я не трогала, потому что вроде есть отдельная таска на рефакторинг toggle в нем есть  сейчас нерабочие , но могу и в рамках этой таски немного порефакторить toggle 
@sergeysova как лучше сделать?

2021-03-25 13:06 UTC, tatinacher commented on src/ui/molecules/toggle/index.tsx
> -      {label && <span style={{ cursor: 'pointer' }}>{label}</span>}
@Irinaristova сделай тогда в следующей таске, где рефакторинг toggle

2021-03-26 08:06 UTC, Irinaristova commented on src/ui/molecules/toggle/index.tsx
> -      {label && <span style={{ cursor: 'pointer' }}>{label}</span>}
ок

2021-03-26 08:26 UTC, tatinacher approved these changes

2021-03-29 15:43 UTC, sergeysova approved these changes

2021-03-29 15:43 UTC, merged