[FRNT-345] fix select
woly-ui/woly pull request #61
Opened 2021-03-26 15:58 UTC by tatinacher

[FRNT-345](https://liberty-base.atlassian.net/browse/FRNT-345)

2021-03-29 11:47 UTC, Irinaristova commented on src/ui/molecules/select/index.tsx
> +  &[data-disabled='true'] {
лучше объединить со стилями на 189 строке

2021-03-29 11:47 UTC, Irinaristova commented on src/ui/molecules/select/index.tsx
>      box-sizing: border-box;
может это свойство просто вынести наверх?

2021-03-29 11:47 UTC, Irinaristova commented on src/ui/molecules/select/index.tsx
> +    div {
стоит ли так ограничивать ширину?

2021-03-29 11:47 UTC, Irinaristova commented on src/ui/molecules/select/example.tsx
> +            setSelect={setValueL}
почему решила переназвать и не использовать onChange?

2021-03-29 11:47 UTC, Irinaristova commented on src/ui/molecules/select/index.tsx
> +  const selectRef = React.useRef<any>();
мб лучше так React.useRef<any>(null) ?

2021-03-29 11:47 UTC, Irinaristova commented on src/ui/molecules/select/index.tsx
> +    [],
мб сюда зависимости передадим?

2021-03-29 11:47 UTC, Irinaristova commented on src/ui/molecules/select/index.tsx
>      margin: 0;
ты тут margin сбрасываешь, а ниже margin-top: 6px, мб сразу прописать?

2021-03-29 11:47 UTC, Irinaristova commented on src/ui/molecules/select/example.tsx
> +  & > * {
тут точно нужно для всех элементов задавать такие стили? это ж вроде только для самих блоков?

2021-03-29 15:51 UTC, sergeysova requested changes

2021-03-29 15:51 UTC, sergeysova commented on src/lib/box-styles.tsx
> +  [data-variant='select-primary'] {
А что это за вариант?

2021-03-29 15:51 UTC, sergeysova commented on src/lib/keyboard-event.ts
> +    setSelect(option);
Почему в библиотеке по обработке события клавиатуры лежит код, который относится к компоненту Select?

2021-03-29 15:51 UTC, sergeysova commented on src/lib/keyboard-event.ts
> +    dropdownNode.firstChild.focus();
Весь код, который не относится к keyboard events не должен лежать здесь

2021-03-29 15:51 UTC, sergeysova commented on src/ui/molecules/select/example.tsx
> +            setSelect={setValueL}
Согласен, тут бы `onChange` с полноценным event

2021-03-29 15:51 UTC, sergeysova commented on src/ui/molecules/select/index.tsx
> +      <ul
```suggestion
      {/* В дальнейшем использовать Popover и List для создания выпадающего списка элементов */}
      <ul
```

2021-03-29 15:51 UTC, sergeysova commented on src/ui/molecules/select/index.tsx
> +    div {
Ширина списка элементов должна равняться ширине Select

2021-04-06 18:52 UTC, sergeysova requested changes

2021-04-06 18:52 UTC, sergeysova commented on src/ui/molecules/select/usage.mdx
> +      change={(event) => event?.target?.getAttribute('data-value')}
```suggestion
      change={(event) => event?.target?.dataset.value}
```

2021-04-06 18:52 UTC, sergeysova commented on src/ui/molecules/select/index.tsx
> +    <>
Не лишний фрагмент тут?

2021-04-06 18:52 UTC, sergeysova commented on src/ui/molecules/select/example.tsx
> +import { ArrowDown } from 'icons';
Давай удалим файл example.ts

2021-04-06 18:52 UTC, sergeysova commented on src/ui/molecules/select/index.tsx
> +        {/* В дальнейшем использовать Popover и List для создания выпадающего списка элементов */}
Можешь завести задачу в беклог на исправление и скинуть мне в слак ссылку на неё ?

2021-04-08 08:46 UTC, sergeysova approved these changes

2021-04-08 08:46 UTC, merged