[FRNT-324] Rewrite Button to formulas and remove icon from right
woly-ui/woly pull request #62
Opened 2021-03-30 14:14 UTC by tatinacher

[FRNT-324](https://liberty-base.atlassian.net/browse/FRNT-324)

Fix buttons sizes, fonts. Remove right button. Update primary colors.

2021-03-30 14:46 UTC, sergeysova requested changes

2021-04-02 08:56 UTC, Irinaristova commented on src/lib/box-styles.tsx
> +  --woly-font-size: 15px;
может вынести это в переменную выше и дальше передавать формулу? просто код дублируется

2021-04-02 08:56 UTC, Irinaristova commented on src/lib/box-styles.tsx
> +  & > * + * {
может просто написать * { - это вроде тоже самое будет? и мб заменить rem на px?

2021-04-02 08:56 UTC, Irinaristova commented on src/lib/box-styles.tsx
> +  & > * + * {
а точно этот margin нужен для всех элементов?

2021-04-02 08:56 UTC, Irinaristova commented on src/ui/atoms/button/example.tsx
> + *          z   Small    | False     |
опечаточка)

2021-04-02 09:45 UTC, sergeysova commented on src/lib/box-styles.tsx
> +  & > * + * {
@Irinaristova `& > * + *` это селектор каждого элемента кроме первого. можно заменить на `& > :not(:first-child)` вроде

2021-04-08 09:40 UTC, sergeysova approved these changes

2021-04-08 09:40 UTC, merged