[FRNT-366] fix surface
woly-ui/woly pull request #64
Opened 2021-04-01 10:56 UTC by tatinacher

Fix surface 
https://liberty-base.atlassian.net/browse/FRNT-366

2021-04-02 08:47 UTC, Irinaristova commented on src/lib/box-styles.tsx
> +  children: (value: any, change: any) => void;
это точно children? может лучше как-то иначе назвать пропс , не используя зарезервированные слова?

2021-04-02 08:47 UTC, Irinaristova commented on src/lib/box-styles.tsx
> +  change: (value: any) => any;
а разве тут нельзя задать типы? например ReactNode?

2021-04-02 08:47 UTC, Irinaristova commented on src/ui/atoms/surface/usage.mdx
> +        <Surface style={{ visibility: value ? 'visible' : 'hidden' }}>
мб эти стили лучше зашить в компонент?

2021-04-02 09:46 UTC, sergeysova commented on src/lib/box-styles.tsx
> +  children: (value: any, change: any) => void;
@Irinaristova точно, это нужно для того, чтобы прокидывать туда функцию.

```jsx
<State>
  {(value, onChange) => <div />}
</State>
```

2021-04-02 09:46 UTC, sergeysova commented on src/lib/box-styles.tsx
> +  change: (value: any) => any;
Думаю, это особо смысла не имеет.
Typescript не может проверить типы в mdx, они там вообще не подсвечиваются, можно забить

2021-04-02 09:48 UTC, sergeysova commented on src/ui/atoms/surface/usage.mdx
> +        <Surface style={{ visibility: value ? 'visible' : 'hidden' }}>
@Irinaristova думаю, тут Таня хотела показать, что surface может выступать как поверхность для всяких модалок.

2021-04-02 09:52 UTC, sergeysova requested changes

2021-04-02 09:52 UTC, sergeysova commented on src/lib/box-styles.tsx
> +  }, [initial]);
Не очень понял эту секцию.

```suggestion
  const [value, setValue] = React.useState(initial);
```

Мб я немного не понял intention, но зачем здесь useEffect, если initial можно сразу закинуть в useState ?

2021-04-02 09:52 UTC, sergeysova commented on src/lib/box-styles.tsx
> +
А вот тут красиво. Люблю упоротые(в хорошем смысле) и красивые решения.

2021-04-02 09:52 UTC, sergeysova commented on src/ui/atoms/surface/usage.mdx
> +</Playground>
Нехватает ещё примеров использования Surface. Если сходу можешь придумать ещё парочку, было бы круто добавить.
Если нет, то просто резолвь этот комментарий

2021-04-07 09:51 UTC, sergeysova approved these changes

2021-04-07 09:52 UTC, merged