[FRNT-335] : add field component
woly-ui/woly pull request #67
Opened 2021-04-07 12:23 UTC by Irinaristova

2021-04-08 11:06 UTC, tatinacher requested changes
Добавляй плз в описание ссылку на задачу в Jira

2021-04-08 11:06 UTC, tatinacher commented on src/ui/molecules/field/usage.mdx
> +    <Field label='Label for a standalone component' variant="default" disabled>
Здесь у label будет состояние disabled, а у TextArea обычное состояние. Т.е. пользователь должен сам помнить о том что нужно и в Field и во внутренний компонент пробросить disabled

2021-04-08 11:06 UTC, tatinacher commented on src/ui/molecules/field/usage.mdx
> +    <Field label='Label for a standalone component' variant="default" disabled>
Тебе тогда для примера надо в TextArea тоже пробросит disabled

2021-04-08 12:25 UTC, Irinaristova commented on src/ui/molecules/field/index.tsx
> +    [data-field='label'] {
так нельзя делать, потому что у тебя ко всем label это применится, а он у тебя не только тут, а еще в ряде компонентов (checkbox, toggle)

2021-04-08 12:25 UTC, Irinaristova commented on src/ui/molecules/field/usage.mdx
> +    <Field label='Label for a standalone component' variant="default" disabled>
я еще работаю над этим пр-ом)

2021-04-08 14:01 UTC, tatinacher commented on src/ui/molecules/field/usage.mdx
> +    <Field label='Label for a standalone component' variant="default" disabled>
👌 я прост накидываю на будущее

2021-04-12 10:49 UTC, tatinacher requested changes

2021-04-12 10:49 UTC, tatinacher commented on src/ui/molecules/field/index.tsx
> +  return (
return можно убрать)

2021-04-12 10:49 UTC, tatinacher commented on src/ui/molecules/field/index.tsx
> +  padding-bottom: var(--woly-vertical, 6px) 0;
зачем тут ноль в конце?

2021-04-12 10:49 UTC, tatinacher commented on src/ui/molecules/field/usage.mdx
> +          id="roundOne"
Поменяй плз id а то будет изменяться на нажатие верхний toggle

2021-04-12 10:49 UTC, tatinacher commented on src/ui/molecules/field/index.tsx
> +  isDisabled,
Ты прокидываешь isDisabled, но ниже нигде не используешь.

2021-04-12 10:49 UTC, tatinacher commented on src/ui/molecules/field/index.tsx
> +      <div data-field="label">{label && <Label>{label}</Label>}</div>
Думаю, на label можно повесить handler по нажатию на него. Юз кейс - switch меняет статус по нажатию на label

2021-04-12 10:52 UTC, tatinacher requested changes

2021-04-12 10:52 UTC, tatinacher commented on src/ui/molecules/field/index.tsx
> +  width: var(--woly-width);
не хватает default значения

2021-04-14 11:44 UTC, sergeysova requested changes

2021-04-14 11:44 UTC, sergeysova commented on src/ui/molecules/field/index.tsx
> +export const FieldBase: React.FC<FieldProps & Variant> = ({
Зачем здесь экспорт?

2021-04-14 11:44 UTC, sergeysova commented on src/ui/molecules/field/index.tsx
> +      </Label>}
Если label не передан, то children не будет отрисован?

2021-04-14 15:40 UTC, sergeysova requested changes
Реши конфликты, пожалуйста

2021-04-14 16:06 UTC, merged