feat(ui): implement checkbox
woly-ui/woly pull request #7
Opened 2020-08-17 09:46 UTC by tatinacher

Implement checkbox atom

2020-08-17 10:09 UTC, sergeysova commented on src/ui/atoms/checkbox/index.tsx
> +export const Checkbox: React.FC<CheckboxProps & { className: string }> = ({
```suggestion
const Checkbox: React.FC<CheckboxProps & { className: string }> = ({
```

Думаю, что пользователю не нужен доступ к базовому компоненту без стилей.

Иначе пользователь получит доступ к `checkbox.Checkbox` и может быть удивлен, почему это верстка расползлась

2020-08-17 10:11 UTC, sergeysova commented on src/ui/themes/index.ts
> +  --checkbox-rounding: 12px;
Тема ничего не должна знать про конкретные компоненты. Давай уберем эти значения прям внутрь компонента. Тему будем проектировать отдельно

2020-08-19 17:00 UTC, sergeysova commented on src/ui/atoms/checkbox/index.tsx
> +export const Checkbox: React.FC<CheckboxProps & { className: string }> = ({
Удалишь `export` ?

2020-08-19 17:02 UTC, sergeysova requested changes
Думаю, лучше удалить export

2020-08-20 08:14 UTC, tatinacher commented on src/ui/atoms/checkbox/index.tsx
> +export const Checkbox: React.FC<CheckboxProps & { className: string }> = ({
@sergeysova сорян, забыла удалить старый Checkbox, компонент лежит в molecules/toggle

2020-08-20 12:36 UTC, sergeysova approved these changes

2020-08-20 12:38 UTC, sergeysova approved these changes

2020-08-20 12:38 UTC, merged