[FRNT- 328] Rewrite input component
woly-ui/woly pull request #73
Opened 2021-04-08 14:31 UTC by Irinaristova

2021-04-08 15:10 UTC, Irinaristova commented on src/ui/atoms/input/usage.mdx
> +### Password input
@sergeysova , @tatinacher  Из этого input можно теперь любой собрать, поэтому добавила пример для password input, если норм так, то InputPassword можно совсем удалить

2021-04-12 13:14 UTC, tatinacher requested changes

2021-04-12 13:14 UTC, tatinacher commented on src/ui/elements/quarks/input-container/index.tsx
> +  &:focus {
В примере фокус бордера пропадает когда начинаешь печатать, а с клавиатуры вообще не подсвечивает.
Бордеры на focus и hover разного цвета в макетах

2021-04-21 12:38 UTC, tatinacher requested changes

2021-04-21 12:38 UTC, tatinacher commented on src/ui/atoms/button-icon/index.tsx
> -}) => {
Почему ты в ветке с задачей исправить Input и InputPassword исправляешь ButtonIcon?

2021-04-21 12:38 UTC, tatinacher commented on src/ui/elements/quarks/input-container/index.tsx
> +      console.log(1);
убрать надо

2021-04-21 12:38 UTC, tatinacher commented on src/ui/elements/quarks/input-container/index.tsx
> +    }
Селекторы не нужны

```suggestion
--local-icon-fill: var(--woly-canvas-text-default);
```

2021-04-21 12:55 UTC, tatinacher requested changes

2021-04-21 12:55 UTC, tatinacher commented on src/ui/elements/quarks/input-element/index.tsx
> +  <input
Проверь состояние disabled, смогла табнуть на инпут с состоянием disabled

2021-04-21 18:10 UTC, Irinaristova commented on src/ui/atoms/button-icon/index.tsx
> -}) => {
потому что эта кнопка была изначально неправильно сверстана и у меня инпут ломался

2021-04-22 09:48 UTC, sergeysova approved these changes

2021-04-22 09:51 UTC, merged