[FRNT-374] : implement headerpanel
woly-ui/woly pull request #74
Opened 2021-04-09 10:50 UTC by Irinaristova

2021-04-10 08:35 UTC, sergeysova requested changes

2021-04-10 08:35 UTC, sergeysova commented on src/lib/box-styles.tsx
> +  --woly-height: 100%;
Высота чего?

2021-04-10 08:35 UTC, sergeysova commented on src/ui/atoms/header-panel/usage.mdx
> +     <HeaderPanel>Hello! It`s a HeaderPanel</HeaderPanel>
Похоже отвалилось форматирование в mdx в VSCode/IDE

2021-04-12 08:21 UTC, Irinaristova commented on src/lib/box-styles.tsx
> +  --woly-height: 100%;
высота может быть у разных компонентов (блока, svg и тд), поэтому я создала более обобщенную переменную, чтобы ее можно было переиспользовать и создавать несколько. мне показалось, что конкретное название для  такой переменной было бы актуально, если высота была бы точным значением

2021-04-12 09:53 UTC, tatinacher requested changes

2021-04-12 09:53 UTC, tatinacher commented on src/ui/atoms/header-panel/index.tsx
> +  width: var(--woly-width);
Мб добавить значение по умолчанию?

2021-04-12 09:53 UTC, tatinacher commented on src/ui/atoms/header-panel/index.tsx
> +import * as React from 'react';
Ненужные импорты можно убрать

2021-04-12 09:53 UTC, tatinacher commented on src/ui/atoms/header-panel/usage.mdx
> +     <HeaderPanel>Hello! It`s a HeaderPanel</HeaderPanel>
Ага, форматирование поехало

2021-04-12 10:21 UTC, Irinaristova commented on src/ui/atoms/header-panel/index.tsx
> +  width: var(--woly-width);
+ и вынести эти переменные лучше наверх, а то мы в каждом компоненте их создаем каждый раз

2021-04-12 14:17 UTC, sergeysova commented on src/lib/box-styles.tsx
> +  --woly-height: 100%;
Переменная обычно используется когда есть смысл менять её значение.

Кажется, что здесь всегда высота будет 100%, как и ширина.

2021-04-14 14:33 UTC, sergeysova requested changes

2021-04-14 14:33 UTC, sergeysova commented on src/ui/atoms/header-panel/usage.mdx
> +name: headerpanel
```suggestion
name: header-panel
```

2021-04-14 15:16 UTC, merged