[FRNT-330] Rewrite Toggle, change name to Switch
woly-ui/woly pull request #75
Opened 2021-04-12 09:37 UTC by tatinacher

Rewrite Toggle, change name to Switch. 
Fix lib/keyboard-events to reuse in different components. 
Update missed imports in ui.

https://liberty-base.atlassian.net/browse/FRNT-330

2021-04-13 12:09 UTC, Irinaristova commented on src/ui/molecules/switch/index.tsx
> +  input:checked + span[data-checkbox] > span:before {
можно просто написать  input:checked + span[data-checkbox] > span {
.....
&:before {....}
}

2021-04-13 12:09 UTC, Irinaristova commented on src/ui/molecules/switch/usage.mdx
> +category: atoms
мб исправить на molecules

2021-04-13 12:09 UTC, Irinaristova commented on src/ui/molecules/switch/index.tsx
> +  isDisabled,
мб задать дефолтное значение и поправить наименование props

2021-04-14 09:45 UTC, tatinacher commented on src/ui/molecules/switch/index.tsx
> +  input:checked + span[data-checkbox] > span:before {
а в чем будет разница?

2021-04-14 10:40 UTC, Irinaristova commented on src/ui/molecules/switch/index.tsx
> +  input:checked + span[data-checkbox] > span:before {
лишняя строка уйдет, зачем дублировать

2021-04-14 11:09 UTC, Irinaristova commented on src/ui/molecules/switch/index.tsx
> +import { Variant } from 'lib/types';
я добавила экспорт Variant в index, чтобы можно  одной строкой все экспортить

2021-04-14 11:12 UTC, Irinaristova commented on src/ui/molecules/switch/index.tsx
> +  const onKeyDown = React.useCallback(
многим компонентам будет нужен этот handler, поэтому мб этот handler просто вынести и сюда импортить, чтобы не дублировать код в разных файлах?

2021-04-14 11:28 UTC, tatinacher commented on src/ui/molecules/switch/index.tsx
> +  input:checked + span[data-checkbox] > span:before {
ага поняла про чо ты)

2021-04-14 11:57 UTC, sergeysova requested changes

2021-04-14 11:57 UTC, sergeysova commented on src/lib/box-styles.tsx
> +    --woly-border-width: 1.5px;
Это же не имеет отношения к варианту, это просто настройка.

2021-04-14 11:57 UTC, sergeysova commented on src/lib/box-styles.tsx
> +    --woly-label-color: #ffffff;
А зачем это здесь?

2021-04-14 11:57 UTC, sergeysova commented on src/lib/box-styles.tsx
> +    --woly-label-color: #ffffff;
Но видимо выпилим это после вмерживания #77

2021-04-14 11:57 UTC, sergeysova commented on src/ui/molecules/switch/index.tsx
> +  );
Я бы предложил сразу называть все локальные `--local`.
А вообще тут проблема, где определены все эти переменные `switcher-height`, `switcher-tumbpler-height`?

2021-04-14 11:57 UTC, sergeysova commented on src/ui/molecules/switch/index.tsx
> +    border-radius: var(--woly-rounding, 18px);
Не стоит использовать default-значения в var(), лучше мы заранее узнаем, что где-то нет правильной переменной, нежели компонент будет скрывать это до последнего

2021-04-14 11:57 UTC, sergeysova commented on src/ui/molecules/switch/index.tsx
> +    input:checked + span[data-checkbox] > span {
Чет меня пугают такие селекторы, зачем так сложно?

2021-04-14 11:57 UTC, sergeysova commented on src/ui/molecules/switch/index.tsx
> +  input:checked + span[data-checkbox] > span:before {
```suggestion
  input:checked + [data-checkbox] > span:before {
```

мне кажется лучше убрать все эти span'ы

Второй селектор `span:before` вообще непонятно что выбирает. Какой span? Что он делает?

тут поможет вменяемый data-атрибут

2021-04-14 11:57 UTC, sergeysova commented on src/ui/molecules/switch/index.tsx
> +    margin-left: var(--woly-gap);
А где определение свойства `--woly-gap`?

2021-04-14 11:57 UTC, sergeysova commented on src/ui/molecules/switch/index.tsx
> +  &:focus > label > span[data-checkbox] > span {
А реально имеет смысл такая вложенность?
нельзя проще?

`&:focus [data-checkbox] span {`

Или вообще сразу дать имя этому span'у и указать на него

2021-04-14 15:23 UTC, Irinaristova commented on src/ui/molecules/switch/index.tsx
> +    border-color: var(--woly-border-focus, var(--woly-background, #000000));
а такая ситуация может быть разве, что цвета в переменной не будет?

2021-04-14 15:23 UTC, Irinaristova commented on src/ui/molecules/switch/index.tsx
> + * --woly-switcher-width
это можно уже удалять наверно

2021-04-14 15:39 UTC, sergeysova commented on src/ui/molecules/switch/index.tsx
> +    border-color: var(--woly-border-focus, var(--woly-background, #000000));
Вообще, нет.
Поэтому любые дефолты по хорошему нужно выпилить

2021-04-15 12:51 UTC, merged