[FRNT-444]  Rewrite checkbox styles
woly-ui/woly pull request #81
Opened 2021-04-14 15:06 UTC by Irinaristova

2021-04-14 15:14 UTC, sergeysova requested changes

2021-04-14 15:14 UTC, sergeysova commented on src/ui/molecules/checkbox/index.tsx
> +          fill: var(--woly-color, #c9c0f8);
Что это за цвет? и почему он постоянно разный?

Смысл переменных в том, чтобы компонент не знал про их значения.
Но при этом, одни и те же переменные использовал бы по назначению.

Сейчас получается, что ты предполагаешь, что переменная будет в разных состояниях компонента разные значения иметь.

2021-04-14 15:23 UTC, Irinaristova commented on src/ui/molecules/checkbox/index.tsx
> +          fill: var(--woly-color, #c9c0f8);
да, ошиблась с переменной, сейчас поправлю

2021-04-15 12:54 UTC, sergeysova approved these changes

2021-04-15 12:54 UTC, sergeysova commented on src/lib/box-styles.tsx
> +    --woly-canvas-text-active: var(--woly-snow-500);
Разлепи пожалуйста обратно на визуальные блоки:
https://github.com/woly-ui/woly/blob/d28cb32500dc2e033b233bfe088e02c31b68db3a/src/lib/box-styles.tsx#L5-L44

Чтобы визуально можно было отделить одно от другого

2021-04-19 14:38 UTC, tatinacher approved these changes

2021-04-22 10:10 UTC, sergeysova commented
Конфликты?

2021-04-23 11:07 UTC, merged