[FRNT-373] Rewrite ButtonIcon
woly-ui/woly pull request #84
Opened 2021-04-15 13:54 UTC by tatinacher

Rewrite ButtonIcon
https://liberty-base.atlassian.net/browse/FRNT-373

2021-04-15 16:31 UTC, sergeysova requested changes

2021-04-16 13:05 UTC, tatinacher commented on src/ui/atoms/button-icon/index.tsx
> +        fill: var(--woly-focus);
Я хотела так изначально сделать, но не получилось, потому что я не знаю какой цвет иконки мне придет изначально, Саша сказал может быть любой. А если делать как в примере выше то цвет заменится тем, что зададим --local-icon-color

2021-04-16 14:42 UTC, tatinacher commented on src/ui/atoms/button-icon/index.tsx
> +        fill: var(--woly-focus);
После встречи разобрали этот вопрос,пофикшу

2021-04-19 10:13 UTC, Irinaristova commented on src/ui/atoms/button-icon/index.tsx
> +    <span>{icon}</span>
этот span лучше как-то назвать все-таки

2021-04-19 10:13 UTC, Irinaristova commented on src/ui/atoms/button-icon/index.tsx
> +  border: 0;
мб тут border скорее всего нужен, просто он должен быть наверно transparent для этого варианта? а если вариант поменяется, изменится и цвет бордера

2021-04-19 10:13 UTC, Irinaristova commented on src/ui/atoms/button-icon/index.tsx
> +  padding: var(--local-vertical);
а горизонтальный padding сколько получается - auto?

2021-04-19 12:06 UTC, tatinacher commented on src/ui/atoms/button-icon/index.tsx
> +  padding: var(--local-vertical);
у button одинаковые паддинги vertical и horizontal

2021-04-19 12:08 UTC, sergeysova commented on src/ui/atoms/button-icon/index.tsx
> +  --local-vertical: calc(1px * var(--woly-component-level) * var(--woly-main-level));
Может тогда назвать его local-padding? Чтобы не запутывать.

2021-04-19 12:08 UTC, sergeysova approved these changes

2021-04-19 16:55 UTC, Irinaristova approved these changes

2021-04-20 08:57 UTC, sergeysova requested changes

2021-04-20 08:57 UTC, sergeysova commented on src/ui/atoms/button-icon/index.tsx
> +    }
```suggestion
    --local-icon-color: var(--woly-shape-text-default);
```

А зачем селекторы здесь?

Переменные же провалятся прям внутрь

2021-04-20 09:29 UTC, tatinacher commented on src/ui/atoms/button-icon/index.tsx
> +    }
Да, точно 👍

2021-04-22 10:15 UTC, sergeysova approved these changes

2021-04-22 10:15 UTC, sergeysova commented
Конфликты?

2021-04-22 12:09 UTC, merged