[FRNT- 450] rewrite menulist
woly-ui/woly pull request #85
Opened 2021-04-15 18:22 UTC by Irinaristova

2021-04-19 12:06 UTC, sergeysova approved these changes

2021-04-20 07:32 UTC, tatinacher requested changes

2021-04-20 07:32 UTC, tatinacher commented on src/ui/molecules/field/usage.mdx
> +`Field` is a master component that will make it easy to modify the label based on the field settings
Field в документации падает

2021-04-20 07:32 UTC, tatinacher commented on src/ui/atoms/list/index.tsx
> +      const tabIndex = disabled ? -1 : 0;
Может стоит вынести блок внутри map в отдельный компонент ListItem?

2021-04-20 07:32 UTC, tatinacher commented on src/ui/atoms/list/index.tsx
> +          console.log(1);
можно убрать

2021-04-20 07:32 UTC, tatinacher commented on src/ui/atoms/list/index.tsx
> +    [data-icon='left'] ~ [data-text],
Здесь ты меняешь паддинг только у элемента справа, но не меняешь паддинг у элемента слева, в итоге у тебя получается gap = padding-right левого элемента + --local-gap, хотя должен быть только --local-gap.

2021-04-20 07:32 UTC, tatinacher commented on src/ui/atoms/list/index.tsx
> +    [data-icon='left'] ~ [data-text],
Можешь поглядеть как в button реализована компенсация

2021-04-20 07:53 UTC, Irinaristova commented on src/ui/atoms/list/index.tsx
> +      const tabIndex = disabled ? -1 : 0;
зачем? он без list использоваться вряд ли когда-то будет

2021-04-20 07:53 UTC, Irinaristova commented on src/ui/atoms/list/index.tsx
> +          console.log(1);
это видимо во всех компонентах так, и в твоих тоже)

2021-04-20 08:02 UTC, Irinaristova commented on src/ui/atoms/list/index.tsx
> +    [data-icon='left'] ~ [data-text],
Комбинатор '~' выбирает элементы, которые находятся на этом же уровне вложенности, после указанного элемента, с тем же родителем, поэтому паддинг устанавливается слева как от [data-text], так и от [data-icon='right'].  В кнопке реализовано также, потому что '+' выбирает элемент, который находится непосредственно после указанного элемента, если у них общий родитель, то есть в данном случае делает тоже самое, только в кнопке иконка присутствует только слева от текста, поэтому правила для элемента справа не прописаны  +  у меня и паддинги иначе немного высчитываются выше у [data-text]
<img width="473" alt="Снимок экрана 2021-04-20 в 11 00 58" src="https://user-images.githubusercontent.com/38761239/115359807-b14b5480-a1c7-11eb-91cf-8a299d3e59fb.png">

2021-04-20 08:04 UTC, Irinaristova commented on src/ui/molecules/field/usage.mdx
> +`Field` is a master component that will make it easy to modify the label based on the field settings
я обновлю пр, а так там все норм)

2021-04-20 08:12 UTC, tatinacher commented on src/ui/atoms/list/index.tsx
> +      const tabIndex = disabled ? -1 : 0;
Мне кажется, что читаемость кода будет лучше

2021-04-20 08:20 UTC, tatinacher commented on src/ui/atoms/list/index.tsx
> +    [data-icon='left'] ~ [data-text],
Я не про комбинатор конкретно говорю, а про то, что когда у тебя появляется иконка (например в случае, когда иконка только слева) ты меняешь паддинг для текста но не меняешь его для иконки (правый паддинг). В итоге получается не local-gap, a  local-gap+правый паддинг иконки.
Визуально видно разницу: 
В дизайн системе:
<img width="500" alt="Снимок экрана 2021-04-20 в 11 19 47" src="https://user-images.githubusercontent.com/28189463/115362558-536c3c00-a1ca-11eb-9812-a432beb5a038.png">

В woly:
<img width="432" alt="Снимок экрана 2021-04-20 в 11 19 19" src="https://user-images.githubusercontent.com/28189463/115362496-43545c80-a1ca-11eb-9987-cb787d3fd291.png">

2021-04-29 09:54 UTC, tatinacher approved these changes

2021-04-30 10:15 UTC, merged