[FRNT-400] Implement Grid and Column
woly-ui/woly pull request #86
Opened 2021-04-16 11:31 UTC by tatinacher

Implement Grid and Column
https://liberty-base.atlassian.net/browse/FRNT-400

2021-04-19 10:04 UTC, Irinaristova commented on src/lib/box-styles.tsx
> +  background: #c9c0f8;
мб тут лучше тоже использовать переменные, а не цвета напрямую?

2021-04-19 10:04 UTC, Irinaristova commented on src/ui/templates/grid/index.tsx
> +  grid-column: var(--local-position);
а откуда эта переменная пришла? она тут вроде нигде не объявлена

2021-04-19 10:04 UTC, Irinaristova commented on src/lib/box-styles.tsx
> +  background: #c9c0f8;
эти вспомогательные компоненты тоже по сути должны же рассчитываться по формулам и меняться в зависимости от размеров

2021-04-19 12:10 UTC, sergeysova requested changes

2021-04-19 12:10 UTC, sergeysova commented on src/ui/templates/grid/index.tsx
> +  grid-column: var(--local-position);
Да, такое лучше задавать из props

```ts
const map = (p: Props) => ({
  style: { '--local-position': p.position, '--local-columns': p.columns },
})
```

Например, так

2021-04-19 16:57 UTC, Irinaristova approved these changes

2021-04-20 08:58 UTC, sergeysova approved these changes

2021-04-20 08:59 UTC, merged