[FRNT-176] Implement Table component
woly-ui/woly pull request #93
Opened 2021-04-21 12:16 UTC by tatinacher

Implement Table component
https://liberty-base.atlassian.net/browse/FRNT-176

2021-04-21 18:51 UTC, Irinaristova commented on src/lib/data.ts
> +export const tableHead = [
это скорее configTable, название data не говорит о том, что лежит в этом файле

2021-04-22 14:47 UTC, sergeysova requested changes

2021-04-22 14:47 UTC, sergeysova commented on src/lib/table-content.ts
> +export const tableHead = [
А зачем это в lib? Это же не библиотечный код, скорее моки.
Мб сразу в usage разместить?

2021-04-23 09:02 UTC, tatinacher commented on src/lib/table-content.ts
> +export const tableHead = [
окей)

2021-04-23 10:00 UTC, Irinaristova commented on src/ui/atoms/table/index.tsx
> +  --local-gap: 3px;
мб лучше использовать константу --woly-m-const: 6px  и с ней производить все вычисления ? так в проекте не будут появляться новые величины

2021-04-23 14:07 UTC, sergeysova approved these changes

2021-04-23 14:18 UTC, merged