[FRNT-327] rewrite select styles
woly-ui/woly pull request #98
Opened 2021-04-26 14:05 UTC by Irinaristova

2021-04-29 09:52 UTC, tatinacher requested changes

2021-04-29 09:52 UTC, tatinacher commented on src/ui/molecules/select/index.tsx
> +  --local-value-color: var(--woly-canvas-text-disabled);
для primary цвет серый, а в макете черный

2021-04-29 09:52 UTC, tatinacher commented on src/ui/molecules/select/index.tsx
> +    box-shadow: 0 0 0 var(--woly-border-width) var(--woly-focus);
В макетах меняется цвет border, а обводки у select нет

2021-04-29 09:52 UTC, tatinacher commented on src/ui/molecules/select/index.tsx
> +    box-shadow: 0 0 0 var(--woly-border-width) var(--woly-focus);
Тут получается для primary вокруг серого бордера появляется фиолетовая обводка

2021-05-04 14:18 UTC, tatinacher requested changes

2021-05-04 14:18 UTC, tatinacher commented on src/ui/molecules/select/index.tsx
> +  --local-select-width: 225px;
Думаю раз везде убираем константы, то тут тоже можно добавить формулу

2021-05-04 14:18 UTC, tatinacher commented on src/ui/molecules/select/index.tsx
> +      fill: var(--local-icon-fill);
По идее цвет у текста и у иконки в select должен совпадать, зачем для иконки создавать отдельную переменную?
В случае variant=secondary иконку не видно

2021-05-04 14:18 UTC, tatinacher commented on src/ui/molecules/select/index.tsx
> +    }
можно заменить на `--local-icon-fill: var(--woly-canvas-text-default);`
ты меняешь только css переменную, селектор для иконки не нужен

2021-05-04 14:18 UTC, tatinacher commented on src/ui/molecules/select/index.tsx
> +    }
тут тоже можно менять только переменную

2021-05-04 14:18 UTC, tatinacher commented on src/ui/molecules/select/index.tsx
> +    }
тут та же ситуация, можно менять просто css переменные

2021-05-04 14:51 UTC, Irinaristova commented on src/ui/molecules/select/index.tsx
> +  --local-select-width: 225px;
и какую тут формулу добавить на width? как он будет расчитываться?

2021-05-04 16:31 UTC, sergeysova commented on src/ui/molecules/select/index.tsx
> +  --local-select-width: 225px;
Ширина селекта должна быть равна инпуту

2021-05-04 16:32 UTC, sergeysova commented on src/ui/molecules/select/index.tsx
> +    }
```suggestion
     --local-icon-fill: var(--woly-canvas-text-default);
```

2021-05-04 16:32 UTC, sergeysova commented on src/ui/molecules/select/index.tsx
> +    }
```suggestion
    --local-icon-fill: var(--woly-canvas-text-default);
```

2021-05-04 16:33 UTC, sergeysova commented on src/ui/molecules/select/index.tsx
> +    }
```suggestion
  --local-icon-fill: var(--woly-canvas-text-disabled);
  --local-background-input-color: var(--woly-canvas-disabled);
  --local-border-input-color: var(--woly-canvas-text-disabled);
  --local-value-color: var(--woly-canvas-text-disabled);
```

2021-05-04 16:34 UTC, sergeysova requested changes
по комментариям выше

2021-05-06 11:59 UTC, tatinacher approved these changes

2021-05-06 11:59 UTC, tatinacher commented on src/ui/molecules/select/index.tsx
> +  disabled,
думаю стоит добавить дефолтное значение

2021-05-07 11:12 UTC, Irinaristova commented on src/ui/molecules/select/index.tsx
> +  disabled,
done

2021-05-07 12:31 UTC, merged